### ISSUE TITLE
License statements missing in crates

### ISSUE THREAD

**Issue by chrysn** [embassy-rs/embassy#1002]
Many crates (eg. embassy-usb) do not have a machine readable `license = "..."` statement. (They're probably the ones not yet on crates.io, for crates.io requires some information to be present around there). From the repository structure it appears like the licensing intention is "Apache-2.0 OR MIT" for the whole project.

Is that correct?

If so, please consider stating that explicitly in the crates. (If it's just about the editing work, I can provide a PR to that effect, but I'd only do that on invitation, for it's a statement I'd be making in my branch already).

In terms of use case, this is motivated by embassy crates having raised flags on a `cargo deny` license check that would otherwise just pass.

**Comment by Dirbaio** [comment]
Yes, it's all Apache+MIT. 

we can add it to all crates even if not realeased on crates.io yet, yes. PR welcome :)
