### ISSUE TITLE
Ability to turn on built-in LED in the RP2040 Pico W

### ISSUE THREAD

**Issue by roguh** [embassy-rs/embassy#1040]
In the Pico W, the LED PIN changed from `GP25` (PIN_25) to a new PIN on the Infineon 43439 WiFi chip called `WL_GPIO0`. I don't see a way to access this PIN from embassy.

The new pinout diagram for reference: ![](https://www.raspberrypi.com/documentation/microcontrollers/images/picow-pinout.svg)

**Comment by Dirbaio** [comment]
It's driven by the WiFi chip, so you'll need the WiFi driver: https://github.com/embassy-rs/cyw43

Then you can use `gpio_set` like this https://github.com/embassy-rs/cyw43/pull/12

**Comment by roguh** [comment]
Thank you.
