### ISSUE TITLE
stm32 HAL DMA SPI read broken

### ISSUE THREAD

**Issue by JoshMcguigan** [embassy-rs/embassy#1095]
Performing a transfer in place correctly reads data from the sensor. Doing the equivalent with a write and then read sends/receives the same bytes over the wire, but the `read` call returns the wrong data.

```
    // In my tests this call was actually done twice, as shown in the logic analyzer trace below
    let mut buf = [0u8, 0];
    embedded_hal_async::spi::SpiDevice::transfer_in_place(&mut spi_dev_1, &mut buf).await.unwrap();
    println!("{:?}", buf);

    let mut buf = [0u8];
    embedded_hal_async::spi::transaction!(&mut spi_dev_1, move |bus| async move {
        bus.write(&buf).await?;
        bus.read(&mut buf).await
    }).await.unwrap();
    println!("{:?}", buf);
```

```
// Output (note the third read, done with a write then read, returns 0 rather than 8)

0.000213 [14, 8]
└─ nucleo_f446re_embassy::____embassy_main_task::{async_fn#0}::{closure#0} @ src/main.rs:62
0.000549 [14, 8]
└─ nucleo_f446re_embassy::____embassy_main_task::{async_fn#0}::{closure#0} @ src/main.rs:66
0.000915 [0]
└─ nucleo_f446re_embassy::____embassy_main_task::{async_fn#0}::{closure#0} @ src/main.rs:73
```

Note each transaction sends/receives the same bits:

![image](https://user-images.githubusercontent.com/22216761/205534811-7a976de4-611d-4f79-a230-6fe22080c0a6.png)

**Comment by rmja** [comment]
I have the same problem. I will try and investigate and get back.

**Comment by rmja** [comment]
@JoshMcguigan Could you verify that my PR resolves the issue?

**Comment by JoshMcguigan** [comment]
This issue (or something similar, write then read returns different data compared to transfer in place) still shows up for me on the latest master branch. I don't have time at the moment to hook up the logic analyzer unfortunately.

**Comment by Redrield** [comment]
Ran into this on 7e251a25, trying to interface with the gyro on the STM32F429I-DISC1. Grabbed a video of what the bus looks like from a logic analyzer, with `spi.write` and `spi.read` back to back in Embassy, vs an STM32Cube based application polling the same register. When I disable rx DMA, embassy's behaviour matches that of Cube

https://user-images.githubusercontent.com/8991639/216128314-610c1785-8ac2-4443-b575-1d487c309d9e.mp4


https://user-images.githubusercontent.com/8991639/216128365-be6a8730-8506-48e5-9188-c40c81dbf45a.mp4

**Comment by Dirbaio** [comment]
i'm going to close this since there's no response from OP and a lot of time has passed. I've never been able to reproduce this and there's been many SPI fixes, so it's likely it's either fixed already or the cause was unrelated to embassy. Feel free to reopen if it still happens and you have oscilloscope traces.
