### ISSUE TITLE
embassy_stm32 docs only contain F42* devices, no others from F4 series

### ISSUE THREAD

**Issue by Xiretza** [embassy-rs/embassy#1116]
The [embassy_stm32 docs](https://docs.embassy.dev/embassy-stm32/git/) don't contain docs for e.g. `stm32f469`. Looking at [the Cargo.toml](https://github.com/embassy-rs/embassy/blob/ebc735008f0b1725b22c944cc5f95fe1aacc665b/embassy-stm32/Cargo.toml#L20) this might be intentional, but why?

**Comment by lulf** [comment]
It might relate to the long docs build time and that there are too many f4 variants, but if you want to test it, you can try running the steps in .github/workflows/doc.yml to see if it impacts the build time significantly.

**Comment by Dirbaio** [comment]
It was for historical reasons, build used to fail for some F4 chips in a hard to fix way, so I excluded them temporarily.

Fixed now, https://docs.embassy.dev now has docs for all stm32 chips.
