### ISSUE TITLE
Handle APPROTECT in revision 3 of nrf52840

### ISSUE THREAD

**Issue by TheButlah** [embassy-rs/embassy#1148]
Revision 3 of the nrf52840 automatically re-enables the APPROTECT feature. Inorder to fix this, we must do some unsafe register manipulation: https://github.com/probe-rs/probe-rs/issues/1324#issuecomment-1356273774

Basically, we must write to `UICR.APPROTECT` location in flash to disable it, as well as write to the `APPROTECT.DISABLE` register.

It would be good if embassy could implement this as part of `embassy_nrf`

**Comment by Dirbaio** [comment]
Fixed in #1170
