### ISSUE TITLE
Is there an ability to export/persist .hex files?

### ISSUE THREAD

**Issue by sureshjoshi** [embassy-rs/embassy#1175]
I'm using Embassy and the NRF Soft Device repo, with the hopes of doing some basic advertising and authentication, on an NRF 52840.

Where I get a bit stuck is that I'm using `nrjprog` to deploy to my firmware, and shipping binary files isn't reliable. Is there the capability to emit a hex file instead?

**Comment by lulf** [comment]
This is the way I've used to generate hex files:

* `cargo install cargo-binutils`
* `rustup component add llvm-tools-preview``
* `cargo objcopy --release -- -O ihex output.hex`

You can use the `mergehex` utility from Nordic to merge this with the softdevice hex to get a single .hex to ship.

**Comment by sureshjoshi** [comment]
Thanks, that's perfect!
