### ISSUE TITLE
USB builder structs not public

### ISSUE THREAD

**Issue by nitroxis** [embassy-rs/embassy#1176]
Hi, is there any reason why the `builder` module of `embassy-usb` [is not public](https://github.com/embassy-rs/embassy/blob/ffa75e1e39949807317ee75459ae9d18b5376578/embassy-usb/src/lib.rs#L9) (or the types re-exported)? For example, `FunctionBuilder` is returned from `Builder`, but is not public. This has caused me some trouble because I can't write helper methods that e.g. add an interface/endpoint, because I can't pass any of the builder structs as parameters.

**Comment by Dirbaio** [comment]
Yes, this is an accidental oversight. All these types should be exported (probably the whole `builder` mod).
