### ISSUE TITLE
Embassy book?

### ISSUE THREAD

**Issue by jerabaul29** [embassy-rs/embassy#1230]
One of the things I liked very much with RTIC was that it came with a nicely written and very pedagogical book that I found very useful and taught me a lot, both technical / practical, but also 'philosophical' / how to think about embedded.

While I understand that RTIC may have needed a book also because it introduces so much non standard, I am wondering: could there be an embassy book, to introduce embassy and take n00bs like me 'by the hand' for helping learn embedded programming and how to think about it in an embassy context? :) .

**Comment by lulf** [comment]
We do have one: https://embassy.dev/book/dev/index.html
