### ISSUE TITLE
embassy_net: should DNS resolve IP adresses without asking the DNS server?

### ISSUE THREAD

**Issue by kbleeke** [embassy-rs/embassy#1237]
I'm using an address like "192.168.178.1:8086" with reqwless. 
This fails with a DNS error since neither reqwless or embassy recognizes this is an IP address and not a hostname.

I think ether reqwless or embassy should handle this case and immediately return an IP if the query is for an IP. Should embassy handle this case? 

I'd add something like this to `Stack::dns_query`
```rust
match qtype {
    dns::DnsQueryType::A => {
        if let Ok(ip) = name.parse().map(IpAddress::Ipv4) {
            return Ok(iter::once(ip).collect());
        }
    }
    #[cfg(feature = "proto-ipv6")]
    dns::DnsQueryType::AAAA => {
        if let Ok(ip) = name.parse().map(IpAddress::Ipv6) {
            return Ok(iter::once(ip).collect());
        }
    }
    _ => {}
}
```

**Comment by lulf** [comment]
I think it makes sense 👍
