### ISSUE TITLE
unresolved import help: a similar path exists: 'stm32_metapac::usb'

### ISSUE THREAD

**Issue by nvankessel** [embassy-rs/embassy#1268]
im trying to build a project for stm32l432kc but it gives the error in title when compiling embassy-stm32

im using the following code:

`
#![no_std]
#![no_main]
#![feature(type_alias_impl_trait)]

use embassy_executor::Spawner;
use embassy_stm32;

use panic_probe as _; 
use defmt_rtt as _;

#[embassy_executor::task]
async fn blinker() {
    loop { }
}

#[embassy_executor::main]
async fn main(spawner: Spawner) {

}

`

In Cargo.toml i have the following code. The statement for 457vg will build, but the 432kc will not.

[dependencies]
embassy-executor = { version = "0.1.0", path = "../embassy/embassy-executor", features = ["nightly"] }
embassy-stm32 = { version = "0.1.0",  path = "../embassy/embassy-stm32", features = ["stm32l475vg"]  }
embassy-stm32 = { version = "0.1.0",  path = "../embassy/embassy-stm32", features = [ "stm32l432kc"]  }
defmt-rtt = "0.3"
cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.0"
panic-probe = { version = "0.3" }

**Comment by Dirbaio** [comment]
make sure to `git submodule update` inside the embassy repo.
