### ISSUE TITLE
LoRa-E5 Dev Board: LoRa problems

### ISSUE THREAD

**Issue by davekingdoms** [embassy-rs/embassy#1273]
Hi,

I have some problems implementing LoRa in my project. I'm using Wio-e5 Dev Board.

First of all, I noticed on TTN gw console that (using OTAA join mode) appeui and devui arrive reversed (appkey is ok).
I bypassed this issue using `.reverse()`. But I think it would be useful to fix it.

In second place, I think there's not enough power getting to the radio. The RSSI is ≈ -100 and SNR is ≈ 2.5 (I'm 1m away from the gateway). 
I tried to run a LoRaWAN example in stm32cubeIde and in that case the radio works fine (RSSI ≈ -25 and SNR ≈ 13).

The last problem is that when the network is joined and I use `device.send()`  only the first message arrives in my app console. The method `.send()` returns a `RxTimeout` error. I think there are some problems with the downlink message. In fact on GW console I see all the subsequent messages, but they are not delivered to app. Maybe the `FCnt` isn't being incremented.

Has anyone run into the same problems?

**Comment by CBJamo** [comment]
devui and join/appeui do not have a specified byte order in the spec, though better documentation would be good. That issue should be raised in the [rust-lorawan](https://github.com/ivajloip/rust-lorawan) crate. 

I suspect the problem with RX power is related to the transmit receive switch. I haven't worked with the stm32wl, so I can't give more guidance than that, but it should point you in the right direction.

```device.send()``` will return an ```RxTimeout``` if there is no downlink queued. Or if your TX/RX switch isn't working or isn't being controlled correctly, then the downlink might not be heard by the radio.

If you have logs from the gateway console and/or from the device, that might help diagnose the last issue. It would also be good to know what chirpstack version the gateway is running.
