### ISSUE TITLE
Unable to run blinky on nrf52840 (Seed XIAO Sense) - CPU resets after await

### ISSUE THREAD

**Issue by yuriykulikov** [embassy-rs/embassy#1275]
I am trying to get https://github.com/embassy-rs/embassy/blob/master/examples/nrf52840/src/bin/blinky.rs running on a https://www.seeedstudio.com/Seeed-XIAO-BLE-nRF52840-p-5201.html

These boards are based on nRF52840 and come shipped with an Adafruit bootloader.

After modifications to `memory.x` and `blinky.rs` I have managed to use LEDs, **but CPU resets after the first `await`**.

Here is my memory.x:

```
MEMORY
{
  FLASH : ORIGIN = 0x27000, LENGTH = 868K
  RAM : ORIGIN = 0x20000000, LENGTH = 256K
}
```

And blinky:

```
#[embassy_executor::main]
async fn main(_spawner: Spawner) {
    let p = embassy_nrf::init(Default::default());
    let mut led_r = Output::new(p.P0_26, Level::High, OutputDrive::Standard);
    let mut led_g = Output::new(p.P0_30, Level::High, OutputDrive::Standard);
    let mut led_b = Output::new(p.P0_06, Level::High, OutputDrive::Standard);

    loop {
        led_r.set_low();
        led_g.set_low();
        Timer::after(Duration::from_millis(5000)).await;
        // never see the blue light, board resets after await returns
        led_b.set_low();
        Timer::after(Duration::from_millis(300)).await;
    }
}
```

Unfortunately I do not have a debugger. Can somebody point me in the right direction?

**Comment by Dirbaio** [comment]
If the flash contains the softdevice (I guess it does since you made flash start at `0x27000`) then you also have to reserve the first 8 bytes of RAM, even if you're not using the softdevice at all. [Source](https://infocenter.nordicsemi.com/topic/sds_s140/SDS/s1xx/mem_usage/mem_resource_reqs.html?cp=5_7_4_0_13_0_0)

so try this:

```rust
  RAM : ORIGIN = 0x20000008, LENGTH = 0x3fff8
```

**Comment by yuriykulikov** [comment]
Thank you @Dirbaio!

This did the trick :)

**Comment by michaelrommel** [comment]
Hello there,

is it possible to add this to the documentation? This took me like 6 hours to find... I think it would be good to have this kind of information somewhere in a board-specific "quirks" document or so. Or have I just been unable to find this despite a lot of effort on my side?

Thanks in advance!!

  Michael.

**Comment by michaelrommel** [comment]
I have now opened up a new issue for the documentation and the provided `memory.x` file, that contains the conflicting information: https://github.com/embassy-rs/embassy/issues/2079

**Comment by tonicospinelli** [comment]
Confirmed. This memory configuration also worked for me using the nRF52840 with SoftDevice S140 v7.3.0.

```rust
MEMORY
{
  /* NRF52840 with Softdevice S140 7.3.0 */
  FLASH : ORIGIN = 0x00000000 + 156K, LENGTH = 1024K - 156K
  RAM : ORIGIN = 0x20000000 + 31K, LENGTH = 256K - 31K
}
```

Reference: [memory-nrf52840.x](https://github.com/embassy-rs/nrf-softdevice/blob/master/examples/memory-nrf52840.x)
