### ISSUE TITLE
Implement `QSPI` (`QuadSPI`) for `stm32`

### ISSUE THREAD

**Issue by Mirror0** [embassy-rs/embassy#1293]
Hello,

I would like to provide an implementation for `QSPI` in `stm32`. I already have an implementation which I successfully used in my project.
@Dirbaio is it something you'd be interested in?

**Comment by Dirbaio** [comment]
Yes, of course! Support for more peripherals is always welcome!

**Comment by Dirbaio** [comment]
fixed in #1294

**Comment by pkoevesdi** [comment]
I'd really appreciate, if there was some usage example of qspi for rust embassy beginners. Is there already something online, i.e. the project You mentioned, @Mirror0?

**Comment by Mirror0** [comment]
@pkoevesdi Unfortunately the project I mentioned is a company internal project not available to public. But I can create some dummy project to illustrate basic usage to my github. I post a link here when I finish it. :)

**Comment by pkoevesdi** [comment]
That would be nice, thank you. If ready I'd suggest to PR this into the example section of this repo here.

**Comment by Mirror0** [comment]
@pkoevesdi I just finished example of QSPI usage. Here is my repo with it: https://github.com/Mirror0/qspi-example. Hope it helps you :)

**Comment by pkoevesdi** [comment]
Great, thank You!
