### ISSUE TITLE
embassy-rp: failed to select a version for the requirement `embedded-hal-nb = "=1.0.0-alpha.2"`

### ISSUE THREAD

**Issue by kbleeke** [embassy-rs/embassy#1337]
Happens when I run `cargo check` in /embassy-rp

I'm a little bit confused, the package seems to exists on crates.io

**Comment by kbleeke** [comment]
This seems to be some problem with the new http-based registry protocol? If I force the old git-based protocol, it works fine

**Comment by Dirbaio** [comment]
Yes, crates.io decided to sabotage the 1.0.0-alpha.2 release. It's being investigated: https://github.com/rust-lang/cargo/issues/11939

**Comment by kbleeke** [comment]
Ah just saw your issue. Nothing to do here, I guess
