### ISSUE TITLE
can find 'embedded-hal-async' crate

### ISSUE THREAD

**Issue by ChinaHDJ1** [embassy-rs/embassy#1344]
<img width="926" alt="image" src="https://user-images.githubusercontent.com/56471245/230771311-7d05306e-7b9b-4fd9-9326-9d8becaef99d.png">
can find when version = "0.2.0-alpha.1"

**Comment by Dirbaio** [comment]
These versions are released. There's something wrong with the IDE tool that you're using, perhaps it hasn't updated the crates.io index yet. 

https://crates.io/crates/embedded-hal-async/0.2.0-alpha.1
https://crates.io/crates/embedded-hal-nb/1.0.0-alpha.2
