### ISSUE TITLE
nrf/ppi: add .trigger() to Task, .is_triggered() and .clear() to Event.

### ISSUE THREAD

**Issue by Dirbaio** [embassy-rs/embassy#1355]
Add
- `Task::trigger()`
- `Event::is_triggered() -> bool`
- `Event::clear -> bool`

Useful for using e.g. `Timer` from manual interrupts instead of from PPI.

**Comment by ilikepi63** [comment]
Hello @Dirbaio 

This is my first crack at this: https://github.com/embassy-rs/embassy/pull/1599

I haven't worked much with the NRF chips and even less on the Task + Event registers. I hope I understood what you were trying to do here.
