### ISSUE TITLE
Missing `async` and DMA support in STM32 I2C v1

### ISSUE THREAD

**Issue by sgoll** [embassy-rs/embassy#1364]
Unless I am mistaken, the STM32 I2C implementation v1 (used by the families F1, F2, F4, L1)[^1] currently lacks `async` functions and DMA support. Instead, only the functions for the blocking, non-DMA access mode are available. Is that correct?

[^1]: The families C0, F0, F3, F7, G0, G4, H5, H7, L0, L4, L5, U5 use the I2C implementation v2.

I was able to find the following issues which do suggest that DMA and `async` had been implemented at one point but I guess these do not apply here:

- https://github.com/embassy-rs/embassy/issues/291#issuecomment-1038420532
- https://github.com/embassy-rs/embassy/issues/269#issuecomment-1038412288

If the v1 implementation never had `async` and DMA support, how hard would it be to add that? Would I be able to follow the gist of #441 and apply it to the v1 implementation?

**Comment by Dirbaio** [comment]
yes, it's just not implemented. There's no reason it can't be done. PR's welcome :)

**Comment by xoviat** [comment]
dup #620
