### ISSUE TITLE
stm32f4: USB cannot be reconnected when using write-only cdc_acm

### ISSUE THREAD

**Issue by KoffeinFlummi** [embassy-rs/embassy#1365]
I'm currently in the process of porting a project (custom board w/ STM32F401, but the issue is reproducible with an F411 black pill) to embassy and have encountered an issue with `embassy-usb`. The STM32 streams telemetry data via USB serial, with the host not (necessarily) sending anything back. When implementing this with embassy, the device seemingly cannot be reconnected:

```
$ dmesg -wH
[...]
# boot with USB connected
[Apr14 00:36] usb 1-11.3: new full-speed USB device number 25 using xhci_hcd
[  +0.159896] usb 1-11.3: New USB device found, idVendor=c0de, idProduct=cafe, bcdDevice= 0.10
[  +0.000016] usb 1-11.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  +0.000006] usb 1-11.3: Product: USB-serial example
[  +0.000006] usb 1-11.3: Manufacturer: Embassy
[  +0.000004] usb 1-11.3: SerialNumber: 12345678
[  +0.019831] cdc_acm 1-11.3:1.0: ttyACM0: USB ACM device
# disconnect
[  +8.830931] usb 1-11.3: USB disconnect, device number 25
# reconnect
[  +1.739238] usb 1-11.3: new full-speed USB device number 26 using xhci_hcd
[Apr14 00:37] usb 1-11.3: device descriptor read/64, error -110
[ +15.573463] usb 1-11.3: device descriptor read/64, error -110
[  +0.179920] usb 1-11.3: new full-speed USB device number 27 using xhci_hcd
[  +3.433610] usb 1-11.3: device descriptor read/64, error -32
```

When booting without the USB port being connected, the first connection will work, but further reconnections won't. To reproduce the issue, I've modified the `usb_serial` example. The original example seems to handle reconnections fine. The relevant part:

```rust
#[embassy_executor::main]
async fn main(_spawner: Spawner) {
    [...] // Unchanged

    // Run the USB device.
    let usb_fut = usb.run();

    // Do stuff with the class!
    let echo_fut = async {
        loop {
            class.wait_connection().await;
            let _ = class.write_packet(b"Testy Testington\n").await;
            Timer::after(Duration::from_micros(1000)).await;
        }
    };

    // Run everything concurrently.
    // If we had made everything `'static` above instead, we could do this using separate tasks instead.
    join(usb_fut, echo_fut).await;
}
```

I have attached logs for both booting with and without USB being connected, with added comments indicating when the (re)connection happens:

[usb_issue_boot_unconnected.log](https://github.com/embassy-rs/embassy/files/11227290/usb_issue_boot_unconnected.log)
[usb_issue_boot_connected.log](https://github.com/embassy-rs/embassy/files/11227292/usb_issue_boot_connected.log)

**Comment by Dirbaio** [comment]
@KoffeinFlummi can you try if #1589 fixes this for you?

**Comment by KoffeinFlummi** [comment]
I did a quick test with the modified usb_serial example on a black pill board and it seems that the problem has been fixed; thank you very much.

However, I could not get the USB connection to work at all with the latest VBUS detection commit (219ef5b3). Nothing in dmesg, stuck on `wait_connection()` forever.

On a2d1e7f0, the example seemed to work perfectly.

**Comment by Dirbaio** [comment]
You need VBUS connected on PA9 possibly with a voltage divider. See AN4789.

Is that on the custom board or on the f411 blackpill? The blackpill simply doesn't seem to be designed to be self-powered, only bus-powered. You should set `vbus_detect=false`. VBUS is not connected to PA9. You could try connecting it externally, but even then it's not compliant (if you power it externally from 5v it'll send power *out* of the usb-c connector which will fight with the 5v from usb. If you power it from 3v3 you have to make sure it doesn't fight with the 3v3 from the U2 regulator, which I don't see any easy way to do other than outright desoldering it lol)
