### ISSUE TITLE
embassy-boot: Copy paste error for SingleFlashConfig

### ISSUE THREAD

**Issue by Lakier15** [embassy-rs/embassy#1393]
It seems that [here](https://github.com/embassy-rs/embassy/blob/0dea7b02d6d320efabede5d7e5470bb0d42cfa88/embassy-boot/boot/src/boot_loader.rs#L465-L473)  the impl for `SingleFlashConfig` is suffering from a copy-paste mistake. The `active`, `dfu` and `state` functions seem to return the wrong types. 

```diff
-    fn active(&mut self) -> &mut Self::STATE {
+    fn active(&mut self) -> &mut Self::ACTIVE {
        self.flash
    }
-    fn dfu(&mut self) -> &mut Self::ACTIVE {
+    fn dfu(&mut self) -> &mut Self::DFU {
        self.flash
    }
-    fn state(&mut self) -> &mut Self::DFU {
+    fn state(&mut self) -> &mut Self::STATE {
        self.flash
    }
```    

It just so happens that functionally there's no difference, as all 3 types are the same. This means that this is merely a refactoring issue.

**Comment by plaes** [comment]
Seems like this functionality was reworked around commit 94046f30ffefc96a7b110ed1d9bb60d64cb4780f and can be closed now.

cc: @Dirbaio
