### ISSUE TITLE
Multiple executor example to run tasks at different priority levels on RP2040.

### ISSUE THREAD

**Issue by overheat** [embassy-rs/embassy#1413]
I have two different things need to manage, time critical motor/sensor control and networking. One fellow suggest using an InterruptExecutor for higher prio tasks with embassy.

I only found a example for nrf52840, [here](https://github.com/embassy-rs/embassy/blob/master/examples/nrf52840/src/bin/multiprio.rs
)

Need example for rp2040

**Comment by overheat** [comment]
@fakusb Thanks for your PR.

I have a question that what if the high priority task is a hardware interrupt, not SWI, let's say I2C1 interrupt?
Can I modify just `SWI_IRQ_1` to `I2C1_IRQ` to let i2c2 interrupt everything else?

**Comment by Dirbaio** [comment]
You can use any interrupt that's unused. If you are really using I2C1, then the I2C driver is using `I2C1_IRQ`, you can't use it for an executor at the same time.

**Comment by overheat** [comment]
> You can use any interrupt that's unused. If you are really using I2C1, then the I2C driver is using `I2C1_IRQ`, you can't use it for an executor at the same time.

Then how to set different priority for different periphal? Let's say I don't want WiFi (spi or pio) interrupt motor driver (pwm)?

**Comment by Dirbaio** [comment]
you control the priorities of tasks, not peripherals. If you spawn a task in a high-priority executor, everything that task does (including the peripheralsit manages) are high priority.
