### ISSUE TITLE
Why cyw43 use pio spi?

### ISSUE THREAD

**Issue by overheat** [embassy-rs/embassy#1514]
Just be curious about this. Because I remember it is normal SPI peripheral for wifi chip connection before.

**Comment by overheat** [comment]
https://github.com/overheat/embassy/blob/82d765689aa0f922d0b43e402eaa3d911b2d461d/cyw43-pio/src/lib.rs

I can only find some comments in the code. Is it related to `overclock`?

**Comment by phire** [comment]
On the Pico W, the SPI pins are not hooked to the correct pins to use the RP2040's normal SPI peripheral. The Pico W PCB also uses resistors to multiples MOSI and MISO (and the cyw43's interrupt request) onto a single GPIO pin, so it's not even proper 4-wire SPI anymore. 
This design allows the Pico W to have the same external GPIO layout as the original Pico, at the cost of needing to use the PIO as a custom SPI implementation.

That previous version might have been for a different PCB that hooked the cyw43 to the proper pins for SPI?

**Comment by 9names** [comment]
@overheat is this question answered sufficiently? if so, would you mind closing the issue?

**Comment by overheat** [comment]
sure.
