### ISSUE TITLE
Would be good to audit interrupt logic

### ISSUE THREAD

**Issue by derekdreery** [embassy-rs/embassy#154]
I had some trouble with an earlier version of embassy because I hit a data race in the way that the interrupts was set to trigger. That issues is fixed now, AFAICT when I look at the code, but I think someone should do a detailed audit of the logic at some point. It's the kind of thing where you can't just wait for bug reports, because if it does cause problems they will be very rare and difficult to reproduce, since they rely on timing.

This isn't a criticism of the code, which looks good, but just a note that an audit would be worthwhile sometime in the future when the codebase has stabilized a bit.

**Comment by Dirbaio** [comment]
I'm going to close this as "not actionable". The exact work tracked here is too vague. Also, almost a year has passed, and the interrupt stuff is quite in a good shape now IMO. It's been a while since I've seen a Waker irq race bug.
