### ISSUE TITLE
Interrupt priority when using bind_interrupts!

### ISSUE THREAD

**Issue by davidtraff** [embassy-rs/embassy#1541]
I'm using nrf-softdevice where the softdevice needs to take interrupt priorities 0, 1 and 4 as stated in the documentation.
But when using SPIM I need to change it's interrupt priority to something higher. But I cannot find a way to do this when using the `bind_interrupts!` macro. How is this done currently?

It might be worth investigating having options in each binding like if its possible:

```rust
bind_interrupts!(pub struct Irqs {
    #[priority(Priority::P2)]
    SPIM2_SPIS2_SPI2 => spim::InterruptHandler<peripherals::SPI2>;
});
```

**Comment by Dirbaio** [comment]
The trouble with `#[priority]` is there is no way to make the macro generate code that runs at boot to set the priority...

You can set it like this at boot:

```rust
use embassy_nrf::interrupt::Interrupt;
embassy_nrf::interrupt::SPIM2_SPIS2_SPI2::set_priority(Priority::P2);
```
