### ISSUE TITLE
I2C slave/peripheral mode support for rp2040

### ISSUE THREAD

**Issue by Ynng** [embassy-rs/embassy#1554]
I2C slave mode is currently not supported on rp2040.

`rp-hal` have an implementation already, would it be straight forward to write a similar implementation based on theirs?
https://github.com/rp-rs/rp-hal/pull/162

**Comment by CBJamo** [comment]
I do have some work[1] done on this front, but got pulled away by other priorities before I could complete it. I was more-or-less copying the interface of the nrf i2c device. The basic functionality works, but needs to be more thoroughly tested. I probably won't be able to get back to this till mid-July, maybe early August.

[1] https://github.com/CBJamo/embassy/tree/i2cdev

**Comment by Ynng** [comment]
Thanks, https://github.com/CBJamo/embassy/tree/i2cdev is working well for me

**Comment by CBJamo** [comment]
This has been merged into embassy-rp. I recommend using a recent git revision, as there are improvements that have not yet been released.

**Comment by Dirbaio** [comment]
closing since this is done now.
