### ISSUE TITLE
Support clock stretching on nrf52

### ISSUE THREAD

**Issue by TheButlah** [embassy-rs/embassy#1557]
Is it possible to support clock stretching on the TWIM peripheral for nrf52840/nrf52832? Some slave devices require it to function, such as the bno080.

**Comment by Dirbaio** [comment]
Clock strething is handled entirely in TWIM hardware, so it is already working.

Beware though there's a bad timing errata in both https://devzone.nordicsemi.com/f/nordic-q-a/48166/i2c-clock-stretching-on-nrf52840 . No workaround exists.
