### ISSUE TITLE
embassy_nrf::uarte::Uarte does not implement embassy_traits::uart::ReadUntilIdle

### ISSUE THREAD

**Issue by rukai** [embassy-rs/embassy#156]
I assume each embassy hal should implement every trait?

**Comment by Dirbaio** [comment]
The UARTE hardware doesn't have this feature. It can be emulated with a timer and 2 PPI channels. 

Implementing it in the driver would force *everyone* to waste 1 timer and 2 PPI channels even if they don't need ReadUntilIdle. We could add it in a separate driver, named something like `IdleUarte`, `UarteWithIdle,`...
