### ISSUE TITLE
How create new project?

### ISSUE THREAD

**Issue by simeondmr** [embassy-rs/embassy#1575]
Hello,

I'm new in Embassy...
How can I create a blank project for example for "stm32g0"?

Thanks

**Comment by k12ish** [comment]
I think this issue has some merit.

- Example `Cargo.toml` files would have to be modified to remove the relative imports:

https://github.com/embassy-rs/embassy/blob/8d50f8a3d3e5a50cd266ca45e221565e5982e744/examples/stm32g0/Cargo.toml#L7-L12

- The wiki is missing a section for creating a new project: 


https://github.com/embassy-rs/embassy/wiki/Getting-Started#create-a-project-using-embassy


Perhaps this issue could be tagged with "Documentation" and "Good First Issue"?

**Comment by snakehand** [comment]
I tried changing the relative paths from an example to git paths, and got 77 errors like this:

154 |         let flush_res = bus.flush().await;
    |                                    -^^^^^
    |                                    ||
    |                                    |`impl ?Sized` is not a future
    |                                    help: remove the `.await`
    |
    = help: the trait `Future` is not implemented for `impl ?Sized`
    = note: impl ?Sized must be a future or must implement `IntoFuture` to be awaited
    = note: required for `impl ?Sized` to implement `IntoFuture`

**Comment by Dirbaio** [comment]
@snakehand you're using a nightly version that has bugs. 

Use this exact version, that's the one supported by Embassy and known to be bug-free: https://github.com/embassy-rs/embassy/blob/main/rust-toolchain.toml#L4
easiest way is to put that `rust-toolchain.toml` file in your project.

**Comment by k12ish** [comment]
Commenting for posterity -- The docs have a section describing [how to setup a new project](https://embassy.dev/book/dev/new_project.html)

[Permalink](https://github.com/embassy-rs/embassy/blob/d832d45c0ba5f2624a5f5c1e549e2d7fe8bd0e01/docs/modules/ROOT/pages/new_project.adoc)

**Comment by lulf** [comment]
The documentation has definitely improved since this issue was raised, closing.
