### ISSUE TITLE
Embassy-stm31f1- on bluepill - flash error

### ISSUE THREAD

**Issue by sundaritisthatis** [embassy-rs/embassy#1651]
Finished release [optimized + debuginfo] target(s) in 0.07s
     Running `probe-run --chip stm32f103c6 target/thumbv7m-none-eabi/release/blinky`
(HOST) INFO  flashing program (15 pages / 15.00 KiB)
Error: Error while flashing

Caused by:
    The execution of 'program_page' failed with code 1. This might indicate a problem with the flash algorithm.

Probes detected -the following probes were found:
[0]: STLink V2 (VID: 0483, PID: 3748, Serial: 300031000C0000363036544E, StLink)

**Comment by Dirbaio** [comment]
Check you have the right chip in Cargo.toml for embassy-stm32. Check that your `memory.x` is correct, in particular that flash is not too big. 

If it still doesn't work, please file an issue for probe-rs.

**Comment by stappersg** [comment]
@sundaritisthatis  do known that open issues consume human energy.

**Comment by andresv** [comment]
Can be closed.
