### ISSUE TITLE
Stm32f401ccu6 - getting started error

### ISSUE THREAD

**Issue by sundaritisthatis** [embassy-rs/embassy#1661]
ERROR probe_rs::cmd::run: Error attempting to attach to RTT: RTT control block not found in target memory.
- Make sure RTT is initialized on the target, AND that there are NO target breakpoints before RTT initalization.
- For VSCode and probe-rs-debugger users, using `halt_after_reset:true` in your `launch.json` file will prevent RTT 
        initialization from happening on time.
- Depending on the target, sleep modes can interfere with RTT. Continuing without RTT...

**Comment by Dirbaio** [comment]
probe-rs 0.20 is now out, fixes this error.
