### ISSUE TITLE
Always make channels Copy

### ISSUE THREAD

**Issue by darkwater** [embassy-rs/embassy#1759]
The current implementation for the embassy-sync channel structs look like:

```rust
/// Send-only access to a [`Channel`] without knowing channel size.
#[derive(Copy)]
pub struct DynamicSender<'ch, T> {
    channel: &'ch dyn DynamicChannel<T>,
}

impl<'ch, T> Clone for DynamicSender<'ch, T> {
    fn clone(&self) -> Self {
        DynamicSender { channel: self.channel }
    }
}
```

The manual Clone impl makes them Clone regardless of whether T is Clone, however Copy is still derived automatically, adding a T: Copy bound. Is there a reason for this, or can we make these all manual impls as well?

**Comment by Dirbaio** [comment]
Yes, Copy should be a manual impl. Nice catch! PR's welcome.

**Comment by darkwater** [comment]
See #1760 

I saw the same pattern for pipes so I did the same thing there
