### ISSUE TITLE
Document the methods on AsyncBufReadExt

### ISSUE THREAD

**Issue by rukai** [embassy-rs/embassy#176]
Document the methods on AsyncBufReadExt

In particular I need a method that will fill the provided buffer with as much data is available but not wait for further data to arrive.

**Comment by Dirbaio** [comment]
Docs are definitely needed. THe io design closely mirrors `futures::io`, you can check that out in the meantime.

> In particular I need a method that will fill the provided buffer with as much data is available but not wait for further data to 
arrive.

You can do that with `.fill_buf()`, polling it just once with `futures::poll!`.

**Comment by lulf** [comment]
I believe this is no longer relevant as the traits have been moved and documented in `embedded-io`.
