### ISSUE TITLE
STM32L4 (others?) RTC clock source config also requires setting PWREN bit

### ISSUE THREAD

**Issue by alexferro** [embassy-rs/embassy#1778]
Issue #1711 (and the accompanying pull request) fixed this in the case of using the LSE for the RTC clock source, but while the LSI can be started without the PWREN bit set, the call to unlock_registers in rtc_v2 waits indefinitely due to the PWR clock being disabled. 

Since the RTC is being unconditionally initialized, the PWREN bit needs to be also set unconditionally, rather than just in the LSE branch.

**Comment by KorribanMaster** [comment]
Have you uploaded your patch for the l4 already so i can try if it fixes it on the f4 (f446) as well ?
