### ISSUE TITLE
Add sponsorships to Embassy org/repos

### ISSUE THREAD

**Issue by Qix-** [embassy-rs/embassy#1855]
Hi Embassy team,

I asked this in Matrix the other day but didn't receive a response. I know a lot of legal paperwork goes into this, but it'd be really nice to somehow sponsor Embassy's ongoing work, even if it's in the form of a small donation. The support from Dario and the team has been exemplary given my experience on Github and I'd like to give back as best as I can. Github sponsorships are a good way of doing this, hence the issue.

Just a thought, looking forward to any means of supporting the project!

**Comment by xoviat** [comment]
The embassy project is not accepting monetary compensation at this time. Individual contributors may accept sponsorship directly.
