### ISSUE TITLE
 info!(

### ISSUE THREAD

**Issue by tcpipchip** [embassy-rs/embassy#1885]
On STM32WL example
lora_lorawan.rs
wich UART PORT is redirect the data of info!(
thanks

**Comment by xoviat** [comment]
probe-run uses rtt to log output, not uart.

**Comment by ceekdee** [comment]
See:

https://github.com/embassy-rs/embassy/issues/1894

for some follow-on discussion.  Are there any known tricks to using the STLINK on an stm32wl when running WSL2 on Windows as a substitute for a Linux kernel?

**Comment by Dirbaio** [comment]
Not sure if WSL supports USB. You can always build inside WSL and run probe-rs outside, though.
