### ISSUE TITLE
feature "low-power" of embassy-stm32: hint for (not) support

### ISSUE THREAD

**Issue by chrenderle** [embassy-rs/embassy#1891]
I wanted to use the feature "low-power" for my stm32l0. I quickly found out, that it is not working because of some compiler errors. Apparently this is not supported for the stm32l0 right now. I tested all stm32 examples and as far as I can tell it is only supported for stm32f4 right now. For every stm32 line there are different compiler errors. 

Before I want to add support for this feature for the stm32l0, I think it makes sense to add a hint that this feature is not supported. Instead of some compiler errors which you have to investigate.

I don't know of any way to do this in a nice way in Cargo.toml as a dependency or something. So I think the best way would be like this (in embassy-stm32/src/low-power.rs):
![image](https://github.com/embassy-rs/embassy/assets/7701334/2c8d79fc-1aff-4aea-aa4c-98da7192a4d5)

Also I would add this condition on rtc_f4 for every other #[cfg(feature = "low-power")] to not get any more compiler warnings, but only the one compile error shown in the image.

Is this the best approach or is there a better one?

**Comment by xoviat** [comment]
low power is a work in progress. I can add support  for each family where there is interest. Can you join matrix to discuss this?

**Comment by chrenderle** [comment]
Yes, I can join Matrix. Although I have no problem doing this myself since I want to contribute more to open-source projects.

**Comment by xoviat** [comment]
Does #1906 resolve this issue for l0?

**Comment by chrenderle** [comment]
I tested it with my NUCLEO-L073RZ board and it didn't work.

What I did was copy the blinky example, enable low-power and run it with log level TRACE. This works so far and I can see that the clock refcount counts down from 2 to 0 in the beginning. When I now set the rtc config to any of the values (RtcClockSource::NoClock, LSE, LSI, HSE) I don't see any output anymore after flashing, so I assume it is crashing somewhere in the initialization, or at least before rtt.

I also tried to set the rtc config with low-power disabled and it is still showing no output. So I assume it is crashing in some code of the rcc->rtc config but not from some code of the low-power feature.

**Comment by xoviat** [comment]
Can you add prints to see where it's getting stuck? Do you need help with that?

**Comment by chrenderle** [comment]
I already solved this problem. What was missing was the power for APB1. I solved this by adding this:
```
// enable APB1 pwr
RCC.apb1enr().write(|w| w.set_pwren(true));
```
before the config.rtc.map call in src/rcc/l0.rs

After that I created a basic blinky code with the low-power executor. For the executor to not panic on an unwrap I had to change the take funktion to take a reference to the rtc to be able to call set_rtc on the RtcDriver. Otherwise it would panic in RtcDriver::stop_wakeup_alarm on the call to borrow.
```
    pub fn take(rtc: &'static Rtc) -> &'static mut Self {
        unsafe {
            assert!(EXECUTOR.is_none());

            let time_driver = get_driver();
            time_driver.set_rtc(rtc);
            EXECUTOR = Some(Self {
                inner: raw::Executor::new(THREAD_PENDER as *mut ()),
                not_send: PhantomData,
                scb: cortex_m::Peripherals::steal().SCB,
                time_driver: time_driver,
            });
            
            EXECUTOR.as_mut().unwrap()
        }
```

With this code the low-power executor is starting, but is hanging on the first Future. The executor is randomly (with the same binary) hanging on different spots. I can't understand why. For example sometimes it hangs right before this critical section line [here](https://github.com/embassy-rs/embassy/blob/7c77d2bd94afcc5dc174f9b3e5c2ce947c6fabb0/embassy-stm32/src/time_driver.rs#L338) and sometimes directly after it. I debugged this via trace! and defmt where I added a trace! before and after exactly this line. 

My blinky code is this:
```
#![no_std]
#![no_main]
#![feature(type_alias_impl_trait)]

use cortex_m::Peripherals;
use cortex_m_rt::entry;
use defmt::*;
use embassy_executor::Spawner;
use embassy_stm32::{gpio::{Level, Output, Speed, AnyPin}, Config, rtc::{RtcClockSource, Rtc, RtcConfig}, low_power::Executor, Peripheral};
use embassy_time::{Duration, Timer};
use embedded_hal::digital::v2::OutputPin;
use static_cell::StaticCell;
use {defmt_rtt as _, panic_probe as _};

static RTC: StaticCell<Rtc> = StaticCell::new();

#[entry]
fn main() -> ! {
    info!("Hello World!");
    let mut config = Config::default();
    config.rcc.rtc = Some(RtcClockSource::LSE);
    let p = embassy_stm32::init(config);
    
    let mut rtc = Rtc::new(p.RTC, RtcConfig::default());
    let rtc: &'static mut Rtc = RTC.init(rtc);

    let executor = Executor::take(rtc);
    executor.run(|spawner| {
        unwrap!(spawner.spawn(blink(p.PA5)));
    });
}

#[embassy_executor::task]
async fn blink(led: embassy_stm32::peripherals::PA5) -> ! {
    let mut led = Output::new(led, Level::High, Speed::Low);
    
    loop {
        info!("high");
        led.set_high();
        Timer::after(Duration::from_secs(10)).await;

        info!("low");
        led.set_low();
        Timer::after(Duration::from_secs(10)).await;
    }
```

**Comment by chrenderle** [comment]
Do you want me to create a PR for the APB1 pwr fix? Or should I create a big PR when I get the low-power executor to run?

**Comment by xoviat** [comment]
You're supposed to use stop with rtc. See the low power test in tests/stm32

**Comment by xoviat** [comment]
You also need to set the time before you call that function

**Comment by chrenderle** [comment]
Ah, I see. It is working now. Thank you.
