### ISSUE TITLE
Using statics

### ISSUE THREAD

**Issue by eleroy** [embassy-rs/embassy#1956]
Hello everyone,

I'm quite new to rust and embassy, but I'm trying it out ! One thing I don't quite get is how I can package for example all of the usb communication in a different module and import it in the main.

I saw in the example usb_serial.rs (for rp2040):
`// Do stuff with the class!
    let echo_fut = async {
        loop {
            class.wait_connection().await;
            info!("Connected");
            let _ = echo(&mut class).await;
            info!("Disconnected");
        }
    };

    // Run everything concurrently.
    // If we had made everything `'static` above instead, we could do this using separate tasks instead.
    join(usb_fut, echo_fut).await;`

I was wondering how one would make everything static, everytime I try I get things like "returns a value referencing data owned by the current function".

I tried also using StaticCell but did not succeed.

It is probably not the right place to ask for this but I think an example of how to structure usb, i2c, etc in a different module would be useful.

Thank you,

Edouard.

**Comment by Dirbaio** [comment]
there's an example here: https://github.com/embassy-rs/embassy/blob/main/examples/rp/src/bin/usb_ethernet.rs

it's essentially putting `make_static!` in the right places so all lifetimes are `'static`.
