### ISSUE TITLE
Restore configuration of RTC for STM32 f7 series

### ISSUE THREAD

**Issue by Mirror0** [embassy-rs/embassy#1957]
Hello,

I'm using the `STM32 f7` series board and after update of embassy the support for RTC configuration for this board is missing. I already re-implement it based on code from repo for `f4`  board, which has implemented this functionality.

@Dirbaio I was wondering if it is something that you are interesting in?

**Comment by Dirbaio** [comment]
yes, of course! PRs adding peripheral support are always welcome.
