### ISSUE TITLE
Crash on startup in wifi_scan rp example

### ISSUE THREAD

**Issue by tommy-gilligan** [embassy-rs/embassy#2064]
I'm brand new to embassy (so not sure this is the appropriate place for something like this)

I kept getting this error
```
0.000204 INFO Hello World!
└─ src/bin/wifi_scan.rs:41
0.272013 DEBUG waiting for clock...
└─ /Users/tom/embassy/cyw43/src/fmt.rs:130
0.272076 DEBUG clock ok
└─ /Users/tom/embassy/cyw43/src/fmt.rs:130
0.272264 DEBUG chip ID: 43439
└─ /Users/tom/embassy/cyw43/src/fmt.rs:130
0.274987 DEBUG loading fw
└─ /Users/tom/embassy/cyw43/src/fmt.rs:130
0.465144 DEBUG loading nvram
└─ /Users/tom/embassy/cyw43/src/fmt.rs:130
0.465961 DEBUG starting up core...
└─ /Users/tom/embassy/cyw43/src/fmt.rs:130
Error: An ARM specific error occurred.

Caused by:
    0: Error using access port
    1: Failed to read register DRW at address 0x0000000c
    2: An error occurred in the communication with an access port or debug port.
    3: Target device did not respond to request.
```

Quite naively I then ran `wifi_blinky.rs` and saw that there was no crash.
So then I copied some blinking to `wifi_scan.rs` to see if it would help.
```
    control.init(clm).await;
    control
        .set_power_management(cyw43::PowerManagementMode::PowerSave)
        .await;

    let delay = Duration::from_secs(1);
    for _ in 1..5 {
        info!("led on!");
        control.gpio_set(0, true).await;
        Timer::after(delay).await;

        info!("led off!");
        control.gpio_set(0, false).await;
        Timer::after(delay).await;
    }

    let mut scanner = control.scan().await;
    while let Some(bss) = scanner.next().await {
        if let Ok(ssid_str) = str::from_utf8(&bss.ssid) {
            info!("scanned {} == {:x}", ssid_str, bss.bssid);
        }
    }
```
And it did!  The blinking fixed `wifi_scan.rs`!  (Probably it wasn't the blinking that fixed it but the delays it introduced)

Testing with and without a delay before `let mut scanner = control.scan().await`:
- Without the delay, sometimes succeeds
- With the delay, it always succeeds

I really don't know the details of what is going on during Wifi initialization.  If there is further debug information that could help please let me know.  It might make sense to just add the delay to the example without worrying too much about the why.

**Comment by Dirbaio** [comment]
how are you powering the Pico W? 

Power it from 5v, not from 3v3. The wifi chip has quite high current spikes that can make it unstable if you power it from 3v3.
