### ISSUE TITLE
Suggestion: Rename `Input::wait_for_high` to `Input::until_high`

### ISSUE THREAD

**Issue by barafael** [embassy-rs/embassy#2092]
Just a suggestion for your consideration. I found waiting async functions and methods nicely readable when they are named `until_`:

```rust
start.until_high().await;
serial.until_packet().await;
```

For reference, right now, this is:

```rust
start.wait_for_high().await;
serial.wait_for_packet().await;
```

Not to bikeshed! But ince there isn't a release yet, I decided to note this here. If you like the idea, I can do the legwork global rename (oh the breakage...). Doesn't need to be global either, perhaps just for GPIO would be fine.

Let me know what you think :)

**Comment by lulf** [comment]
I think embassy should follow the conventions from embedded-hal (https://docs.rs/embedded-hal-async/1.0.0-rc.1/embedded_hal_async/digital/trait.Wait.html).

**Comment by barafael** [comment]
Fair, OK!
