### ISSUE TITLE
nrf Qspi write (and maybe read) fails with zero-length buffer

### ISSUE THREAD

**Issue by peter9477** [embassy-rs/embassy#2115]
The Qspi peripheral in embassy-nrf allows you to pass in a zero-length buffer, but it appears doing this will probably stall the future.  I think what happens is that the QSPI peripheral will not generate EVENTS_READY if the CNT is zero.

Although this is trivial to avoid by adding a check in calling code, given the outcome I think it's probably wise to add a check in at least the `write()` routine (and probably also `read()`).  It should be reasonable to just return immediately in that case rather than returning an error.

Note also that although this will only stall the current future (because the interrupt never fires to wake the waker), an even more serious problem occurs if you try wrapping the future with a `with_timeout()` (or otherwise trying to drop the future).  If you do that, the OnDrop's `blocking_wait_ready()` call becomes an infinite busy-loop, and kills the entire executor.

**Comment by Dirbaio** [comment]
nice find! adding a check to immediately return if len=0 sounds good to me, could you send a PR?
