### ISSUE TITLE
embassy_rp::critical_section_impl race condition on reset

### ISSUE THREAD

**Issue by phire** [embassy-rs/embassy#2191]
If the critical section happens to be taken during reset, then spinlock 31 can remain taken throughout reset.

This does get cleared when `embassy_rp::init()` resets most peripherals, but that doesn't run until main. And embassy_executor take a critical section at some point during Executor initialisation (there might be more, but mine got stuck in `allocate_alarm`.

A somewhat crude workaround is to just register a `pre_init` function with cortex_m_rt and clear the spinlock:

```rust
#[cortex_m_rt::pre_init]
unsafe fn pre_init() {
    // Reset spinlock 31
    core::arch::asm!("
        ldr r0, =1
        ldr r1, =0xd000017c
        str r0, [r1]
    ");
}
```

But we probably want a better solution, maybe someway for HALs to register some early init code to run before initialising the constructor. Or maybe the `embassy_executor::main` macro needs to run the entire HAL init before the executor?

**Comment by Dirbaio** [comment]
dup of #1736
