### ISSUE TITLE
stm32 low power mode is a bad design!

### ISSUE THREAD

**Issue by skyarm** [embassy-rs/embassy#2195]
Why do not using the RTC as Timer alone?  The STOP state must be waked up every 32 seconds,  To mixed the RTC and Timer  in low power mode is a bad design!

**Comment by Dirbaio** [comment]
Opening an issue on an opensource project saying "this is bad design!" without considering there might be reasons why it's that way is not nice.

If you're interested on what these reasons are feel free to try again, asking nicely.
