### ISSUE TITLE
STM32G0 I2C incompatable with newer embassy-stm32 

### ISSUE THREAD

**Issue by Ralim** [embassy-rs/embassy#2253]
Hia,

It appears in [bc65b8f7ec1df181c793846b7c0657f689963d3a](https://github.com/embassy-rs/embassy/commit/bc65b8f7ec1df181c793846b7c0657f689963d3a) the implementation was updated to use the error and event interrupts separately.

On the STM32G0 chips there is only interrupt 23 for I2C1 and interrupt 24 for I2C2/3. These are used for both the EV/ER interrupts together.

Is there any plan to support this combined IRQ or do I need to write a shim to remap this back out?

I'm using the `stm32g070cb` locally at the moment.

It [looks](https://github.com/embassy-rs/stm32-data-generated/blob/65dd4d0c19a2a0c6e0a86a71098d756ff045093f/data/chips/STM32G070CB.json#L670) as though the meta package is generating doubled entries for the two of these with the same name . ([comparison F4](https://github.com/embassy-rs/stm32-data-generated/blob/65dd4d0c19a2a0c6e0a86a71098d756ff045093f/data/chips/STM32F429AI.json#L2388))

Love the work ❤️, this is not urgent as I dont need newer features yet :)

**Comment by Dirbaio** [comment]
You can do it like this.

```rust
bind_interrupts!(struct Irqs {
    I2C1 => i2c::EventInterruptHandler<peripherals::I2C1>, i2c::ErrorInterruptHandler<peripherals::I2C1>;
    I2C2_3 => i2c::EventInterruptHandler<peripherals::I2C2>, i2c::ErrorInterruptHandler<peripherals::I2C2>,
        i2c::EventInterruptHandler<peripherals::I2C3>, i2c::ErrorInterruptHandler<peripherals::I2C3>;
});
```
