### ISSUE TITLE
How to import embassy stm32 dependency

### ISSUE THREAD

**Issue by FranciscoAmaro24** [embassy-rs/embassy#2316]
The `embassy-stm32` crate is only recognized as the ```0.0.0``` version. How can I import the `0.1.0` version

**Comment by lulf** [comment]
The current version 0.0.0 is there as a placeholder until the first version is released. In the meantime you have to depend on embassy-stm32 using a git dependency, ideally using `[patch.crates-io]` for all embassy dependencies to ensure they are aligned.
