### ISSUE TITLE
stm32g4: wrong ADC version

### ISSUE THREAD

**Issue by lights0123** [embassy-rs/embassy#2362]
The STM32G4 has an [ADCv3 peripheral](https://docs.google.com/spreadsheets/d/1-R-AjYrMLL2_623G-AFN2A9THMf8FFMpFD4Kq-owPmI/edit?pli=1#gid=1972450814&range=P22), but this crate (and stm32-data) has it configured as an ADCv4, introduced in https://github.com/embassy-rs/embassy/pull/1867 and https://github.com/embassy-rs/stm32-data/pull/244. This is seen in differences with the [reference manual](https://www.st.com/resource/en/reference_manual/rm0440-stm32g4-series-advanced-armbased-32bit-mcus-stmicroelectronics.pdf), where the available resolution and sample times differ.

**Comment by Dirbaio** [comment]
fixed in #2791
