### ISSUE TITLE
I2C for NRF

### ISSUE THREAD

**Issue by AliMoal** [embassy-rs/embassy#2419]
Hi everyone,
I need to know is there any plan to implement I2C peripheral for NRF family? I mean embassy-nrf
As I searched there is no i2c in NRF HAL neither. Could anyone help me for this? I see It has implemented for embassy-stm32

**Comment by lulf** [comment]
This is already implemented, but it's named TWI (two wire interface): 

* https://github.com/embassy-rs/embassy/blob/main/examples/nrf52840/src/bin/twim.rs
* https://docs.embassy.dev/embassy-nrf/git/nrf52805/twim/index.html

**Comment by AliMoal** [comment]
I didn't know that.
Thanks.
