### ISSUE TITLE
OnceLock-like type

### ISSUE THREAD

**Issue by robertbastian** [embassy-rs/embassy#2503]
I'm looking for a type like `std`'s [`OnceLock`](https://doc.rust-lang.org/std/sync/struct.OnceLock.html). In an async world it would have an API like 
* `pub const fn new() -> Self`
* `pub async fn get(&self) -> &T`
* `pub fn set(&self, T) -> Result<(), T>`

That is, it can be placed in a `static`, everyone waits for someone to put a value value in, and then everyone gets a shared reference. Any further calls to `get` resolve immediately, any further calls to `set` fail.

Does this exist? I found `Signal`, but its `wait` returns `T` by value, so it must remove the value  (the doc explanation is cyclic but the type is pretty clear). Can this be trivially assembled from existing types in embassy? Is this impossible to do?

**Comment by asasine** [comment]
I think this is completed as of #2651.
