### ISSUE TITLE
embassy-stm32: Port Octospi & Hyperbus from STM32H7xx-hal

### ISSUE THREAD

**Issue by VegaDeftwing** [embassy-rs/embassy#2514]
Reference https://github.com/stm32-rs/stm32h7xx-hal/blob/master/src/xspi/octospi.rs

Octospi (often using Hyperram) is necessary for some designs which use it to dramatically expand the amount of available RAM. This is a feature on some F4, F7, G4, H5, H7, L4, L5, U5, and WB5 chips.

**Comment by Dirbaio** [comment]
https://github.com/embassy-rs/embassy/pull/2672 added octospi support.
