### ISSUE TITLE
Unaligned buffer in embassy-boot async firmware updater for RP2040

### ISSUE THREAD

**Issue by chamburr** [embassy-rs/embassy#2542]
When using the async firmware updater for RP2040, all operations to update the magic code fails with an unaligned error.

This can be traced to changes made in #2411, after which the aligned buffer must have a size of 4 due to READ_SIZE being the larger size, and being defined as 4 for RP2040.

https://github.com/embassy-rs/embassy/blob/2c5426aa5c41563f3b225d99d39793a765ec9204/embassy-boot/src/firmware_updater/asynch.rs#L229-L230

This becomes a problem for the set magic function, which calls the flash read function for both offset 0 (line 274) as well as 1 (line 278). This is because WRITE_SIZE is defined as 1 for RP2040.

https://github.com/embassy-rs/embassy/blob/2c5426aa5c41563f3b225d99d39793a765ec9204/embassy-boot/src/firmware_updater/asynch.rs#L273-L278

This eventually triggers an error in the flash background read function for RP2040, which requires that the offset is a multiple of 4 (lines 286 to 288).

https://github.com/embassy-rs/embassy/blob/2c5426aa5c41563f3b225d99d39793a765ec9204/embassy-rp/src/flash.rs#L270-L288

**Comment by lulf** [comment]
Thanks for the bug report! I'm wondering if the best fix here is to make the magic of size `STATE::WRITE_SIZE.max(STATE::READ_SIZE))` all over then.

**Comment by chamburr** [comment]
Hmm... This doesn't sound like a simple fix with READ_SIZE being different for sync and async flash. I suspect we also have to change the magic size in the blocking firmware updater and the boot loader, and it would be something like max of sync read, sync write, async read and async write sizes?
