### ISSUE TITLE
STM32H503: enabling RTC causes startup crashes and UB

### ISSUE THREAD

**Issue by tcbennun** [embassy-rs/embassy#2546]
Been banging my head against a wall about this for a while now.

I have the NUCLEO-H503RB. If I take the `stm32h5` blinky example and make minimal changes:

- change the chip to the H503RB
- change task arena to 16384 or lower (to fit in the small memory of the H503)
- change the blinky pin to PA5 to match the board

... then I get a hard fault somewhere during RCC init, sometimes; other times, I get corruption on the stack.

By default, RTC is enabled by default and is set to source from the LSI. If I change the example main as follows:

```rust
    let mut config = Config::default();
    config.rcc.ls = LsConfig::off();
    let peris = embassy_stm32::init(config);
```

then everything appears to be okay again.

The same thing happens if I use `LsConfig::default_lse()` (which should work, the Nucleo has an external crystal for LS on board).

I see there's a notice in the code that there's a similar issue with L5. Wonder if it's the same thing.

**Comment by tcbennun** [comment]
I've narrowed it down to these lines.

https://github.com/embassy-rs/embassy/blob/26fc17e8a7db0957896db28cb2299ab9cf89aea5/embassy-stm32/src/rcc/bd.rs#L206

Forcing a backup domain reset followed by immediate writes to RCC_BDCR is clearly problematic

**Comment by Dirbaio** [comment]
I can't reproduce this on my NUCLEO-H503RB. Can you provide exact code (a branch on a fork for example) and exact `cargo run` command to reproduce? thanks!

**Comment by tcbennun** [comment]
> I can't reproduce this on my NUCLEO-H503RB. Can you provide exact code (a branch on a fork for example) and exact `cargo run` command to reproduce? thanks!

Sorry, didn't see this until now, I'll provide something soon

I'm hoping I haven't damaged all my boards in some weird specific way...

**Comment by tcbennun** [comment]
@Dirbaio 
https://github.com/tcbennun/nucleo-h503rb-minimal-rs

**Comment by Dirbaio** [comment]
okay, I was able to reproduce the issue with your repo. thank you! :) 

Turns out the issue is this gem of an errata. If I set `memory.x` to only use SRAM1 the corruption no longer happens.

![screenshot-2024-02-22_20-50-06](https://github.com/embassy-rs/embassy/assets/1247578/95b71886-e0ba-4a8c-af2b-39e9f18c370b)

I'm ... not sure how to workaround that.

**Comment by tcbennun** [comment]
Thank you so much for digging and finding that!

I'll need to work around it somehow, pretty mission critical. I reckon I can hack my use case so nothing critical is in SRAM2 at the point of backup domain reset (should only be during init). We shall see...
