### ISSUE TITLE
[embassy-rp] Support unsafe creation of AnyPin instance

### ISSUE THREAD

**Issue by adsnaider** [embassy-rs/embassy#2577]
Hi, I believe a `pub unsafe fn new(id: u8) -> Self` should be appropriate within `AnyPin`. Unless I'm just not finding the correct way to construct a pin based on the pin number at runtime. Happy to submit a PR for this.

**Comment by Dirbaio** [comment]
this exists in the other HALs, it's called [`steal`](https://github.com/embassy-rs/embassy/blob/5220453d85b1e0f279e94dc1627b7d2434132920/embassy-stm32/src/gpio.rs#L714-L720). Would be nice to have it on rp too, a PR would be very welcome.

**Comment by adsnaider** [comment]
Thanks, opened PR https://github.com/embassy-rs/embassy/pull/2581
