### ISSUE TITLE
Clarification on RTOS capabilities

### ISSUE THREAD

**Issue by ndrscodes** [embassy-rs/embassy#2644]
Hey there,

From the docs, it doesn't become clear if tasks scheduled on the same executor will block each other. For example, let's say i wanted to create a task that looks something like this:

```rust
loop {
    loop {
        cortex_m::asm::nop();
    }
    //what should i await here?
}
```

and there is another task that looks like this:
```rust
loop {
    //some really important work here
    //something that should be awaited
}
```

would the really important work be executed even though the first task is running in an endless loop, never awaiting anything?

Additionally, this raises the question of what to await if there is no interrupt etc. to await. I could await `Timer::after_millis(1)` or something along these lines. But that would defeat the purpose of awaiting something in the first place.

Thanks in advance!

**Comment by lulf** [comment]
Tasks scheduled on the same executor will block each other, so if one task is refusing to await/yield, the other task will never run. There is no preemption of tasks.

If you need real time, what you're looking for is to create multiple executors where you configure them to run on different priority levels and schedule high priority tasks on the high priority executor etc.

**Comment by ndrscodes** [comment]
@lulf thank you for the clarification. Does this mean then that, if a task which is not using `await` is running on a separate executor, the framework will ensure that tasks on a separate, higher priority executor will run, thus suspending the long running task?

**Comment by ndrscodes** [comment]
This is awesome, thank you so much for the clarification. I think, the docs should be a little clearer about how this system works in detail. If i find the time, i'll have a look at the code and might submit a PR to clarify the behaviour (if i manage to understand it).
On a personal note: I love what you have created here. I am just starting out on embedded rust, but embassy has already found it's place as my go-to framework. I love the HAL you created for the STM32, working with inputs and outputs just feels right. A minor inconvenience was that the docs follow the main branch. The crates don't do this and as such, the docs sometimes don't match the available API. But other than that, working with embassy has nothing but awesome so far. Keep it up!

**Comment by koutheir** [comment]
As far as I understand, the term "real time" has nothing to do with performance or priority of tasks. A system qualified as "real time" only refers to its ability to **guarantee a maximum time latency** between (1) the time an interrupt is received, and (2) the time the handler of that interrupt starts running. Because of this definition, a system can, for example, be qualified as "real time" while being fairly slow to operate, if that guarantee can still be provided for some time latency X.

Using `async`/`await` in Rust, by definition, follows a cooperative multitasking approach, which, as far as I imagine, cannot provide such guarantees, unless the runtime implementation **also** preempts these futures. Does *embassy* preempt tasks?

@lulf, please let me know if I'm missing something.

**Comment by Dirbaio** [comment]
as I wrote above, you can use multiple executors at different priorities to get preemption: https://github.com/embassy-rs/embassy/blob/main/examples/stm32f4/src/bin/multiprio.rs

**Comment by koutheir** [comment]
Do you mean to implement real time preemption, manually, based on high priority timer interrupts? If that is the case, then this would be like implementing a real time operating system scheduler/dispatcher, and *embassy* would still not **provide** real time multitasking.

**Comment by Dirbaio** [comment]
Check out the example: you don't use interrupts manually, you spawn tasks at higher priorities, and they preemot lower priority tasks whenever they need to run (e.g. when a timer expired, when some byte arrived over an uart, etc...)

**Comment by koutheir** [comment]
> they preemot lower priority tasks whenever they need to run

Does this mean that a lower priority task is immediately preempted even if it wants to run for a long time (I know that async tasks should not do that, but I have to assume this possibliity), or does this mean that high priority tasks are scheduled first the next time a cooperative task yields?

**Comment by Dirbaio** [comment]
> Does this mean that a lower priority task is immediately preempted even if it wants to run for a long time

Yes, that's what preemption means.

**Comment by koutheir** [comment]
Good, thank you for the clarification.

**Comment by showier-drastic** [comment]
May I ask a question: is it possible to use channels to communicate between the tasks in the multiprio example?

**Comment by ndrscodes** [comment]
Hi @showier-drastic :) 

I have learned a bunch of things since creating this question. Yes, you can use channels to communicate between executors, but in that case you have to use the correct kind of Mutex. You will have to use a `CriticalSectionRawMutex` for this.
