### ISSUE TITLE
AsyncWrite

### ISSUE THREAD

**Issue by DanielMadmon** [embassy-rs/embassy#2661]
Is there an equivalence to Tokio::AsyncWrite?

**Comment by Dirbaio** [comment]
yep! https://docs.rs/embedded-io-async/latest/embedded_io_async/trait.Write.html

**Comment by DanielMadmon** [comment]
Thank you, is there an example for usage within embassy?

**Comment by Dirbaio** [comment]
Embassy implements the traits for stuff like UART, and embassy-net TCP. Here's one example of it being used in a TCP socket: https://github.com/embassy-rs/embassy/blob/60567b72fb8807bf72aa28f0e2c551953c1ef7bf/examples/rp/src/bin/wifi_tcp_server.rs#L146

you can search the repo for more https://github.com/search?q=repo%3Aembassy-rs%2Fembassy%20embedded_io_async&type=code

**Comment by lulf** [comment]
I'm considering this answered, reopen if not.
