### ISSUE TITLE
duplicate lang item in crate `std` (which `embedded_io_async` depends on): `panic_impl`

### ISSUE THREAD

**Issue by 0xkelvin** [embassy-rs/embassy#2678]
i am not sure if here is the right place to ask. 
but i really need help. 

i building standalone project on esp32c6 with embassy framework. Below is Cargo.toml and error msg : 
<img width="1281" alt="image" src="https://github.com/embassy-rs/embassy/assets/56182747/b1c9361f-ece4-433e-b5fb-595b20394629">

Appreciate any help

**Comment by Dirbaio** [comment]
I *think* what's happening here is you're mixing `esp-hal` and `esp-idf-hal` (pulled in by `esp-idf-svc`). You can't use `esp-idf-svc` in a bare-metal `esp-hal` project.

This is a esp32-specific issue though, you'll have better answers asking in the esp-hal repo or the esp-rs Matrix channel, not here.

**Comment by 0xkelvin** [comment]
thanks
