### ISSUE TITLE
stm32: async hal implementations

### ISSUE THREAD

**Issue by FrozenDroid** [embassy-rs/embassy#269]
I thought it'd be good to have a tracking issue for this, so people can coordinate work on this topic

- [ ] USART
- [ ] I2C
- [ ] SPI
- [ ] ADC
- [ ] Delay
- [ ] GPIO

**Comment by lachlansneff** [comment]
Don't forget the new async Delay trait and the async pin traits that are now in the PR.

**Comment by bobmcwhirter** [comment]
Is this in reference to some `embedded-hal` async variants, or within Embassy's own async traits?

**Comment by FrozenDroid** [comment]
This is within Embassy's own traits. Currently the STM32 hal only mostly has blocking APIs.

**Comment by bobmcwhirter** [comment]
Ah, right on.

So we've made pretty good progress with USART and SPI for all versions, and @thalesfragoso has a soon-to-land PR for I2C. They were all awaiting DMA implementation, which we now have behind us.

There's async Delay also in-tree for STM32.

**Comment by Dirbaio** [comment]
All the features in OP are suppored in embassy-stm32 now.
