### ISSUE TITLE
STM32 BufferedUart receive task gets woken-up too late

### ISSUE THREAD

**Issue by jr-oss** [embassy-rs/embassy#2719]
BufferedUart wakes receive task only when the whole buffer has been filled or the line is idle, no matter how many bytes the user tries to read.
https://github.com/embassy-rs/embassy/blob/3845288ffb0418cc375430dd366a1a49ccee6f5a/embassy-stm32/src/usart/buffered.rs#L55-L62

My use case is a RS485 line with echo, i.e. the uart also receives all bytes, that it sends.
I send part of data via `BufferedUartTx` and read the line echo byte for byte via `BufferedUartRx` while still appending new tx data to the buffer between read attempts.

Sometimes I get a gap in tx data of about one character time.
This happens, when I `read()` from `BufferedUartRx` while the underlying buffer is still empty and the task goes to sleep.
It only wakes up, if the line is idle, which happens about 1 character time after sending all tx data.
After that the next tx part can be sent.

My expectation is, that `read(&mut byte_buffer)` returns (latest), when `byte_buffer` has been filled.

Which solution is preferable?
- wake up for each character, which may cause excessive wake-ups
- wake-up, when a threshold is reached, which requires modifications in `RingBuffer` to get a `fill_level()` incl. getting the atomic operations right
- something completely different

I could prepare a PR for the first two options (and maybe for the third one, also)

The implementation for RP seems to wake the receive task for any number of received bytes
https://github.com/embassy-rs/embassy/blob/3845288ffb0418cc375430dd366a1a49ccee6f5a/embassy-rp/src/uart/buffered.rs#L545-L548

**Comment by Dirbaio** [comment]
Changing it to waking at every byte (like embassy-rp) sounds good to me. iirc other people have run into issues with this too.
