### ISSUE TITLE
Should the future returned by `embassy_time::Ticker::next` be `Send + Sync + 'static`?

### ISSUE THREAD

**Issue by Frostie314159** [embassy-rs/embassy#2748]
In exploring the possibilities for an `embedded-hal-async` trait for `Ticker`s I noticed, that the future returned by the function mentioned in the title isn't `Send + Sync + 'static`. Is this intentional? My tests so far have shown, that adding this bound doesn't negatively effect the tests I ran.

**Comment by Dirbaio** [comment]
`Timer` and `Ticker` could be Send+Sync, yes. a PR for this would be welcome : )
