### ISSUE TITLE
PR2040 PWM naming

### ISSUE THREAD

**Issue by alexandruradovici** [embassy-rs/embassy#2758]
We are using embassy for a embedded class in Rust. Students have been confused by the naming convention used by embassy for the PWM. The PR2040's datasheet states that there are 8 PWM slices, each of them having two channels.

Embassy defines the `PWM_CH_X` data type for the slice, not for a channel. Students have been confused by the fact that they cannot use channel 0 (actually 0B) for Pin 1 (https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/issues/84). Our suggestion would be to rename the data type to `PWM_SLICE_X` to reduce confusion. 

If this is something that you might consider, we would be happy to submit a PR. To preserve compatibility with older code, we can define type alias to `PWM_CH_X`.

**Comment by Dirbaio** [comment]
you're right, renaming would be better.

> To preserve compatibility with older code, we can define type alias to PWM_CH_X.

don't worry about it, next release of embassy-rp is going to have breaking changes anyway.
