### ISSUE TITLE
[`Sync`]: Add support for `map` methods

### ISSUE THREAD

**Issue by c410-f3r** [embassy-rs/embassy#2768]
Hello,

Is it possible to add `map` methods for Mutex guards? For example, tokio has https://durch.github.io/rust-goauth/futures/lock/struct.MappedMutexGuard.html#method.map.

The standard library also has a `map_split` (https://doc.rust-lang.org/std/cell/struct.RefMut.html#method.map_split) for `RefMut` if that is relevant.

Thanks

**Comment by Dirbaio** [comment]
this would be a nice addition, I've needed this myself some time in the past. Would you be willing to implement and PR it?

**Comment by c410-f3r** [comment]
#2782
