### ISSUE TITLE
State of `embassy_extras/usb`

### ISSUE THREAD

**Issue by dexterduck** [embassy-rs/embassy#280]
I was wondering what the current status of the USB module in `embassy_extras/usb` is. As far as I can tell, it's currently unusable because the `Usb` object requires an interrupt that implements `USBInterrupt`, which no interrupts currently do.
Is that an intentional choice to prevent use of the module for the moment? If so, what functionality is missing for the module to be usable?

**Comment by Dirbaio** [comment]
`embassy_extras` is intended to provide stuff to embassy HALs (`embassy-nrf`, `embassy-stm32`, ...). Not intended to be used for end users. We should maybe rename it to `embassy-hal-common` to make that clearer.

The USB stuff is meant for HALs to wrap it, wiring it up with `stm32-usbd`, `nrf-usbd`, etc and reexport that as a "ready to use async USB api". It's just not done yet. There was an impl for stm32f4 a while ago, but it got removed when we redid `embassy-stm32` to work on all stm32 chips. It has to be added again.
