### ISSUE TITLE
Allow using embassy-time Timer with embassy_futures::block_on

### ISSUE THREAD

**Issue by brt-adam-snaider** [embassy-rs/embassy#2830]
I'm happy to send a PR to do this, but I'm just not sure if there's a reason this wouldn't work to begin with.

The reason this would be useful for us is that we write tests as async functions but we execute them serially using embassy_futures::block_on.

For the record, this is the panic message I get when I try to do this

```
ERROR panicked at 'Found waker not created by the Embassy executor. `embassy_time::Timer` only works with the Embassy executor.'
```

**Comment by Dirbaio** [comment]
You can fix this by enabling feature `generic-queue` in `embassy-time` and disabling feature `integrated-timers` in `embassy-executor`.

**Comment by brt-adam-snaider** [comment]
Works for me, thank you!
