### ISSUE TITLE
cargo objcopy and arm-none-eabi-objcopy output differs

### ISSUE THREAD

**Issue by shufps** [embassy-rs/embassy#2843]
I had the problem of a malfunctioning firmware on one of my boards and it turned out that it makes a difference if you flash it with

```
cargo run --release --bin mybin
```

or export it as binary with 

```
cargo objcopy --release --bin mybin -- -O binary mybin.bin
```
and then upload with `dfu-util`.

When comparing both binaries it turns out that they are totally different (via downloading from the STM32 device)

On the other hand, 
```
arm-none-eabi-objcopy -O mybin.bin  -S ./target/thumbv7m-none-eabi/release/mybin
```
generates the exact same binary as uploaded via `cargo run`.

Has someone an idea what might go wrong with `cargo objcopy`?

Thx in advance!

**Comment by Dirbaio** [comment]
this is not an Embassy bug, so i'm going to close it.

I don't know what could be wrong. `cargo objcopy` uses `llvm-objcopy`, maybe try that to see whether it's cargo-objcopy's fault or llvm-objcopy's fault. Maybe try `rm -rf target`, maybe try setting --target manually in case it's using the wrong elf...
