### ISSUE TITLE
Possible to use embassy API with esp32?

### ISSUE THREAD

**Issue by Gibbz** [embassy-rs/embassy#2873]
I've been using esp-hal on the esp32c3, but the syntax and API is terrible to work with. Is there a wrapper available so that I can use the embassy methods and API with the esp chips?

**Comment by Dominaezzz** [comment]
> but the syntax and API is terrible to work with

Care to elaborate?
Which embassy APIs did you have in mind?

**Comment by jwhitlark** [comment]
The esp-hal repo has a number of embassy examples (anything that starts with `embassy_`) at https://github.com/esp-rs/esp-hal/tree/main/examples/src/bin.

Or were you looking for more than that?

**Comment by Gibbz** [comment]
I've moved to using a nrf chip now...
