### ISSUE TITLE
Search broken in docs.embassy.dev

### ISSUE THREAD

**Issue by plaes** [embassy-rs/embassy#2955]
Search feature for some (if not all) crates (embassy-executor, embassy-nrf) seems to be broken as it attempts to pull a  `crates.js` file.

For example:
* https://docs.embassy.dev/embassy-executor/git/cortex-m/index.html?search=executor
* https://docs.embassy.dev/embassy-nrf/git/nrf52832/index.html?search=output

Output from console:
![image](https://github.com/embassy-rs/embassy/assets/91895/b0546b18-4396-44df-937d-dd99ce42e22b)

What seems to be happening (for example with `embassy-nrf` docs:
1. HTML refers to `<script defer src="../crates.js"></script>`
2. When attempting to load it, it does `302 redirect` to `location: /embassy-nrf/git/nrf52832/`
3. `/embassy-nrf/git/nrf52832/` returns html instead of javascript.

**Comment by JuliDi** [comment]
Looks like that script load should be removed. But the regex no longer matches, there is a `defer=""` added in the produced files.
https://github.com/embassy-rs/docserver/blob/1c857fbfabeb5e9f313ff5114fc90a7a00d9f459/src/bin/builder.rs#L32-L34

I attempted to fix this, will make a PR shortly.
