### ISSUE TITLE
USB Endpoint struct is no longer Send

### ISSUE THREAD

**Issue by mattico** [embassy-rs/embassy#2957]
Previously at least `<embassy_stm32::usb::Driver<'d, USB_OTG_HS> as Driver<'d>>::EndpointIn` was `Send`, but after #2881 it contains an `UnsafeCell<*mut u8>` and therefore isn't `Send`. Perhaps we just need an `unsafe impl Send for Endpoint<_>` but I haven't thought carefully about whether that's safe or not.

**Comment by Dirbaio** [comment]
maybe `unsafe impl Send/Sync for EpState` is a less heavy hammer and should still do it. the previous code already had that for `State`.
