### ISSUE TITLE
allow to have TICK_HZ value other than ones already in the list

### ISSUE THREAD

**Issue by djdisodo** [embassy-rs/embassy#2961]
i'm trying to make driver for embassy_time
https://github.com/djdisodo/avr_tc0_embassy_time

for example on arduino uno, the source clock is 16MHz

and if i use 64 Prescalar that's 16MHz/64 so 250000Hz

(i used 256_000Hz for testing, which should be close enough)

i can just upscale/downscale the ticks every time but it adds a bit of complexity,

also i don't want to create preset to account for different source clock

i have an idea,

it's still nightly feature but by using `proc_macro_tracked_env`

[macro crate link](https://github.com/djdisodo/env_int/blob/master/src/lib.rs)

```rust
const TICK_HZ: usize = env_int!(TICK_HZ, 16000000);
```
you can do something like this, this will default to 16000000 if TICK_HZ environment variable isn't defined

and will use TICK_HZ as value if possible, only recompiles when TICK_HZ value is changed

**Comment by Dirbaio** [comment]
I'd prefer to not add a new dependency just for this. It's possible to do it with no deps, from build.rs. See how `ekv` does it: https://github.com/embassy-rs/ekv/blob/main/build.rs

If you want to send a PR for that, it'd be great.

Also, we can simply add the needed tick rates too.
