### ISSUE TITLE
Add Mutex

### ISSUE THREAD

**Issue by eupn** [embassy-rs/embassy#30]
A no_std version of [tokio mutex](https://tokio-rs.github.io/tokio/doc/tokio/sync/struct.Mutex.html), [async-std mutex](https://docs.rs/async-std/1.9.0/async_std/sync/struct.Mutex.html). Similar to [this mutex](https://github.com/rust-embedded-community/async-on-embedded/blob/master/async-embedded/src/unsync/mutex.rs).

**Comment by huntc** [comment]
Is this essentially closed given https://github.com/embassy-rs/embassy/blob/master/embassy/src/blocking_mutex/mod.rs?

**Comment by Dirbaio** [comment]
No, this issue is about an async mutex, where you can `.lock().await`. The one we have is blocking.

**Comment by vito-chl** [comment]
Is there a plan to develop it？

**Comment by Dirbaio** [comment]
Yes. 

In the meantime, you can use [futures-intrusive's Mutex](https://docs.rs/futures-intrusive/latest/futures_intrusive/sync/index.html), it works great with embassy.

Also, PRs are welcome :)

**Comment by lulf** [comment]
This is fixed and part of embassy now
