### ISSUE TITLE
Signal and !Send types?

### ISSUE THREAD

**Issue by jvatic** [embassy-rs/embassy#3051]
I'm wondering if there's a reason why the [implementation of `Signal` specifies `T: Send`](https://github.com/embassy-rs/embassy/blob/d06dbf3/embassy-sync/src/signal.rs#L68)? It seems to me that this is handled by the type of mutex used, am I missing something?

**Comment by Dirbaio** [comment]
true, I can't think of a particular reason to require it. Try removing it, if nothing breaks then a PR would be welcome.
