### ISSUE TITLE
Large arena causes memory errors and strange behaviour?

### ISSUE THREAD

**Issue by mkj** [embassy-rs/embassy#3061]
I've been trying to track down an issue where using a relatively large arena size (larger than 131072?) on a pico w causes what seems like a memory overwrite. The arena isn't full, and no panic seems to occur.

Compiling with `nightly` feature seems to resolve the problem. 

I've pushed a modified `wifi_tcp_server` example that triggers the problem. Failures are usually a hang before wifi initialises, though the current exact size triggers a panic in smoltcp, which is why I suspect perhaps memory overwrite somewhere. The extra 91000 byte allocation is somewhere near the boundary where the problem starts appearing (from rough bisection).

https://github.com/mkj/embassy/commit/2589482e7486950a536fb7f3495ac60165097ebd
The test case works on nightly (f21554f7f 2024-06-08) or 1.78.0 (with the `feature` commented out obviously)

```
DEBUG LOGS: 000000.642 wl0: wl_open
└─ cyw43::runner::{impl#1}::log_read::{async_fn#0} @ /home/matt/3rd/rs/embassy/cyw43/src/fmt.rs:130 
WARN  IRQ DATA_UNAVAILABLE, clearing...
└─ cyw43::runner::{impl#1}::handle_irq::{async_fn#0} @ /home/matt/3rd/rs/embassy/cyw43/src/fmt.rs:156 
ERROR panicked at /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smoltcp-0.11.0/src/iface/interface/mod.rs:1443:9:
assertion failed: !ip_repr.dst_addr().is_unspecified()
└─ panic_probe::print_defmt::print @ /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/panic-probe-0.3.0/src/lib.rs:91  
```

Any suggestions on how to debug further?

**Comment by dvdsk** [comment]
try setting up probe-rs as a debugger: https://probe.rs/docs/tools/debugger/

then call break when the program hangs. You will probably find you end up in the fault handler with a bus error. To solve it try saving space somewhere. On nightly the arena is sized automatically to just the right size saving a bit of memory. Try lowering the amount of ram you use (shrink arrays and objects if you can).

**Comment by mkj** [comment]
Yep, I'll try and have a look at the actual fault.
The arena fits in available RAM (otherwise it wouldn't link), and the tasks fit in the arena (otherwise it would panic), so I don't think it's an issue of sizes - something else is going wrong.

**Comment by Dirbaio** [comment]
You have to leave enough RAM for the stack. The stack starts from end of RAM and grows downwards. If it grows too much, it will crash into static data, causing UB. This is not checked at link time because the linker doesn't know how much stack your program uses.

**Comment by mkj** [comment]
Sorry for the noise, looks like it was just stack size. I was assuming the array in the example was part of task memory, but passing it to `black_box()` (by value not reference) instead results in another stack copy.
