### ISSUE TITLE
Clean up STM32 examples

### ISSUE THREAD

**Issue by bobmcwhirter** [embassy-rs/embassy#307]
Remove old-PAC usage for RCC if RccPeripheral is implemented enough.

So we can stop copy/pasting stuff that isn't needed into new examples.

**Comment by bobmcwhirter** [comment]
@timokroeger Would you consider this "done" for now?

**Comment by timokroeger** [comment]
Let’s keep it open until we have `embassy::main` for all series (e.g. #319). I will work on that the coming days.
Moving `DbgMcu::enable_all()` to `embassy::main` would be another outstanding cleanup task. But I can track this in another issue.

**Comment by bobmcwhirter** [comment]
Right on, no worries at all. Much appreciation for what you're doing!

**Comment by timokroeger** [comment]
I think this issue can be closed now

**Comment by Dirbaio** [comment]
:ok_hand:
