### ISSUE TITLE
NRF missing peripheral pins

### ISSUE THREAD

**Issue by Gibbz** [embassy-rs/embassy#3155]
I have a nrf52840 and some of the pins are unavailable for use:
p0_09
p0_10

Is there a reason these pins are not available for use?

**Comment by Dirbaio** [comment]
Enable cargo feature `nfc-pins-as-gpio` in Cargo.toml.

**Comment by Gibbz** [comment]
Thanks, thats done it :+1: 
Noticed theres also one for the rest pin too!

```
## Allow using the NFC pins as regular GPIO pins (P0_09/P0_10 on nRF52, P0_02/P0_03 on nRF53)
nfc-pins-as-gpio = []

## Allow using the RST pin as a regular GPIO pin.
##  * nRF52805, nRF52810, nRF52811, nRF52832: P0_21
##  * nRF52820, nRF52833, nRF52840: P0_18
reset-pin-as-gpio = []
```
