### ISSUE TITLE
Build failures after new `usbd-hid` release

### ISSUE THREAD

**Issue by calebstewart** [embassy-rs/embassy#3183]
I just tried to initialize a new project, and was met with an error during building related to `usbd-hid`. It seems this is related to a package versioning bug in `usbd-hid`. I *think* the solution is to update the `usbd-hid` dependency in `embassy-usb` to `0.8.2` (from `0.7.0`). Essentially, `0.8.0` introduced breaking changes, and earlier versions were not properly version restricted. The result is that it seems that `usbd-hid` v0.7.0 pulls in `usbd-hid-descriptors` v0.8.2, which don't work together. That's all assuming I understand the problem correctly.

[Upstream Issue](https://github.com/twitchyliquid64/usbd-hid/issues/72)

**Comment by Dirbaio** [comment]
should be fixed in #3181
