### ISSUE TITLE
Do a release of `embassy-usb`?

### ISSUE THREAD

**Issue by HaoboGu** [embassy-rs/embassy#3194]
Hello! `usbd-hid` released 0.8, caused https://github.com/embassy-rs/embassy/issues/3183. 

#3181 fixed it, but for users who uses crates.io version of `embassy-usb`(which depends on usbd-hid 0.7), the dependency still breaks, see logs here: https://github.com/HaoboGu/rmk/actions/runs/9984504140/job/27593827945

Is it possible to do a new `embassy-usb` release? :D

**Comment by lulf** [comment]
Done! https://crates.io/crates/embassy-usb
