### ISSUE TITLE
STM32G0: USB Clock select enum USBSEL is wrong

### ISSUE THREAD

**Issue by ijager** [embassy-rs/embassy#3223]
I am trying to configure the USB peripheral to use the `PLL_Q` clock as USB Clock (for use as Host).

The expectation is that this can be done with

```rust
 config.rcc.mux.usbsel = mux::Usbsel::PLL1_Q;
```

With `PLL1_Q = 0x01` which matches the value in the manual RM0444.

However this value appears to be wrong. `0x01` configures USB to use HSE instead.

PLLQCLK and HSE are swapped _both_ in the manual as in the embassy `pac`.

Correct values:

```rust
pub enum Usbsel {
  HSI48 = 0x0 ,
  HSE = 0x01 , 
  PLL1_Q = 0x02 ,
  _RESERVED_3 = 0x03
} 
```

See also this person on this forum who found the same issue https://klipper.discourse.group/t/stm32g0-usb-clock-config/4487

**Comment by Dirbaio** [comment]
fixed in https://github.com/embassy-rs/stm32-data/pull/512
