### ISSUE TITLE
TM1637 display protocol - desired for Embassy

### ISSUE THREAD

**Issue by marxin** [embassy-rs/embassy#3250]
Just recently, I made a working TM1637 display using the GPIO ports with the Embassy framework. The code is mostly based on this: https://rust-classes.com/chapter_embedded_pi_input_tm1637.

Is the community interested in upstreaming the protocol into the Embassy?

**Comment by lulf** [comment]
Rather than upstreaming that in embassy, it is generally preferable to implement drivers using traits from the various [embedded-hal](https://github.com/rust-embedded/embedded-hal) crates, which will allow the driver to work with not only Embassy but other HALs and other runtimes.

**Comment by marxin** [comment]
Then, there's probably existing an implementation that depends on `embedded-hal`: https://github.com/igelbox/tm1637-rs
