### ISSUE TITLE
STM32 USB Serial example doesnt work 

### ISSUE THREAD

**Issue by jas1339** [embassy-rs/embassy#3276]
I was trying to follow the usb serial example for STM32H7 and i get the following error that it couldnt find usb in embassy_stm32:
![image](https://github.com/user-attachments/assets/69076cc7-6030-4a5a-bbf4-c853201acd85)

I was able to find a usb_otg in embassy_stm32. The example requires updating or I might be missing something.

**Comment by Dirbaio** [comment]
if you use the examples from latest git, you have to use embassy-stm32 from latest git.

**Comment by jas1339** [comment]
I'm using the latest git. I have embassy-stm32 as 0.1.0 and I can see the usb folder in embassy-stm32, but it's not showing up in the code.
