### ISSUE TITLE
Change formatting of embassy-usb-logger

### ISSUE THREAD

**Issue by Kezii** [embassy-rs/embassy#3294]
Am I missing something or is it impossible to change the style / formatting of the embassy-usb-logger?
Ideally I should be able to override this default with my own style with log levels etc.

https://github.com/embassy-rs/embassy/blob/f0a86070512ad739641cee7d9fa39d63f5c8a9f6/embassy-usb-logger/src/lib.rs#L140

**Comment by lulf** [comment]
Yes, it's pretty basic, though you should be able to [configure the log level](https://docs.rs/log/0.4.22/log/fn.set_max_level.html).

Probably the way to go is to provide your own 'log' crate implementation, and perhaps expose whatever methods necessary on the usb-logger crate to do what you want.
