### ISSUE TITLE
NRF52840 USB: Blocking until I open the device on host

### ISSUE THREAD

**Issue by Murmele** [embassy-rs/embassy#3389]
I am using the usb capability of the NRF52840 with embassy to send some data to the host using Cdc Acm.

If I open on my linux machine cutecom and connect to the virtual serial device I get all data, but if I close the application the write_packet() blocks the complete microcontroller. It would be nice if there is a non blocking functionality.

It is blocking because
```rust
impl<'d, T: Instance, Dir> Endpoint<'d, T, Dir> {
    async fn wait_data_ready(&mut self) -> Result<(), ()>
```
in embassy-nrf
Maybe extending the usb drive by a timeout?

```rust
pub struct Driver<'d, T: Instance, V: VbusDetect> {
    _p: PeripheralRef<'d, T>,
    alloc_in: Allocator,
    alloc_out: Allocator,
    vbus_detect: V,
    timeout: Timeout,
}

pub enum Timeout {
    No,
    InUSeconds(usize),
}
```

### Steps to reproduce
1. Create a small usb task and let it send data.
2. Create a second task which has some debug output
3. Start application on microcontroller.
4. The second task is completely blocked
5. Open an serial port application on the host system
6. Connect
  - Data send by the microcontroller is visible
  - Debug output of the second task is visible

```rust
// Create classes on the builder.
    let mut class = CdcAcmClass::new(&mut builder, state, 64);

    // Build the builder.
    let usb = builder.build();

    info!("Spawn usb task");
    match spawner.spawn(usb_task(usb)) {
        Ok(_) => (),
        Err(_) => (),
    }

    info!("Wait for connection");
    class.wait_connection().await;
    info!("Connected");

    loop {
        let buffer_mutex = BUFFER_CHANNEL.receive().await;
        let mut guard = buffer_mutex.lock().await;
        guard.status = Status::Free;

        info!("Received");

        if let Err(_) = class.write_packet(&guard.buffer).await {
            info!("Failed to send packet");
        }
        info!("Finished write");
        guard.buffer.clear();
    }
```

**Comment by HaoboGu** [comment]
You can always add timeout to any async function using: https://docs.embassy.dev/embassy-time/git/default/fn.with_timeout.html
