### ISSUE TITLE
Add Cargo.lock files

### ISSUE THREAD

**Issue by gibbz00** [embassy-rs/embassy#3405]
Repeating the question form https://github.com/embassy-rs/trouble/issues/134

Why aren't there any Cargo.locks? Is the purpose to not have reproducible builds and make things harder to debug?

**Comment by Dirbaio** [comment]
Yes, we like our debugging as hard as possible. \s

Embassy crates are libraries. When building a project, Cargo uses the Cargo.lock from the top-level binary crate, lockfiles from libraries are not used.

So adding Cargo.lock wouldn't help reproducibility or prevent breakages for Embassy users, and it'd add clutter and conflicts to the repo and maintenance headache.
