### ISSUE TITLE
LTDC register configuration seems to be wrong on STM32U5

### ISSUE THREAD

**Issue by williams-one** [embassy-rs/embassy#3457]
When using LTDC driver with a RGB screen on STM32U5 the image is corrupted. Basically, a square is not shown with vertical sides but with diagonal size, since each line is offset by some pixel with respect to the previous one.

The configuration of CFBLR register seems to require some adaptations on U5.
As per section "43.7.23 LTDC layer x color frame buffer length register (LTDC_LxCFBLR)" of Reference manual for STM32U5 RM0456, CFBLL has to be set to the length of one pixel line plus 3 (instead of plus 7 as for H7)

Changing the settings for the registry as described the image was rendered in a more reasonable way.
I have a small patch and an example.  I can submit a PR if required.

Even after this fix, however, the image was not completely correct.  Vertical lines of 1 px were rendered in a fuzzy way (too wide or too thin), as if timings were not correct, even though I put in exactly the same parameters taken from the IOC of the source code generated for the demo board by CubeMX.
In order to get a proper image, I also had to reverse all the polarities for HSYNC, VSYNC, DATA_ENABLE and PIXEL_CLOCK with respect to the settings taken from IOC.

Do you have additional suggestions on what to check and how to additionally troubleshoot the issue with the display parameters?

**Comment by Dirbaio** [comment]
>  CFBLL has to be set to the length of one pixel line plus 3 (instead of plus 7 as for H7)

WTF ST, why? :roll_eyes: 

>  I have a small patch and an example. I can submit a PR if required.

that would be awesome!

(sorry I can't give input on how to further troubleshoot, I don't know much about LTDC. hopefully someone else can)

**Comment by williams-one** [comment]
> WTF ST, why? 🙄
That's the same thing that I thought after one day of debugging...

I've opened a PR here https://github.com/embassy-rs/embassy/pull/3458
I've seen it's already red 😅
On Monday I will have a look at why it failed and fix it

> (sorry I can't give input on how to further troubleshoot, I don't know much about LTDC. hopefully someone else can)
Thanks for the feedback for now.  Next week I will try asking on matrix
