### ISSUE TITLE
How to set bit of RCC_AHB4ENR_GPIOEEN?

### ISSUE THREAD

**Issue by J-F-Liu** [embassy-rs/embassy#3481]
In C, there is `SET_BIT(RCC->AHB4ENR, RCC_AHB4ENR_GPIOEEN)`
With stm32_hal
```
if rcc.ahb4enr.read().gpioeen().bit_is_clear() {
    rcc.ahb4enr.modify(|_, w| w.gpioeen().set_bit());
}
```
How to do this in embassy?

**Comment by Dirbaio** [comment]
you shouldn't need to do it, `embassy_stm32::init()` already enables GPIOxEN for you.

(you do register writes with the PAC:  `embassy_stm32::pac::RCC.ahb4enr().modify(|w| w.set_gpioeen_true));`)
