### ISSUE TITLE
Imprecisions in `embassy-time-driver` API

### ISSUE THREAD

**Issue by carloskiki** [embassy-rs/embassy#3487]
I am implementing the time-driver for a chip, and I have some questions that are not answered by the docs:
- Once the caller has allocated an alarm, should it assume that it is still allocated after the alarm has rang? This is what I understand from the implementation on stm32 boards.
- Should the caller be expected to set the callback before each call to `set_alarm`? I think the answer is no, from the stm32 driver as well.

I think these cases should be added to the docs of the `Driver` trait as it would benefit implementers. I am ready to open a PR once I have answer to the questions.

**Comment by Dirbaio** [comment]
>  Once the caller has allocated an alarm, should it assume that it is still allocated after the alarm has rang? This is what I understand from the implementation on stm32 boards.

Yes, an alarm is a "reusable" resource, you can set it and fire it as many times as you want.

> Should the caller be expected to set the callback before each call to set_alarm? I think the answer is no, from the stm32 driver as well.

No need, no.

> I think these cases should be added to the docs of the Driver trait as it would benefit implementers. I am ready to open a PR once I have answer to the questions.

Please do! that'd be great.
