### ISSUE TITLE
[STM32C0] Using TIM14 as a time driver

### ISSUE THREAD

**Issue by thunderstorm010** [embassy-rs/embassy#3581]
Hi, I'm trying to use time on my STM32C011F6 chip. I am currently using TIM1 and TIM3 for PWM outputting, so I don't have any timer left that has a feature gate time-driver-xxx. After reading the datasheet, it seems that i can use TIM14 for it. Is it possible?

**Comment by eZioPan** [comment]
No, I don't think TIM14 can be used as a time driver, it only has 1 CC channel:

https://github.com/embassy-rs/embassy/blob/04c1d69de9d5f0d9285015daba631aeef123b00e/embassy-stm32/src/time_driver.rs#L21-L30
