### ISSUE TITLE
Question about embassy error handling

### ISSUE THREAD

**Issue by joebnb** [embassy-rs/embassy#3648]
hello,i’ve been learning embedded development for a few days, and I noticed that synchronous execution flow becomes a bottleneck when executing multiple tasks simultaneously. then I found that embassy, based on the event loop, solves this issue. however, I have a question regarding error handling.

and my question is:

it seems that embassy doesn’t support the '?' operator to propagate errors. the main function doesn’t accept any return values, and tasks also can’t return results.

how can I handle errors in a simpler way?

**Comment by thunderstorm010** [comment]
Well, there is no where to forward an error if an error exists.
What you can do is using something like defmt to log your errors to your debugger.
You may also use some kind of permanent storage to log your errors to view them later (for example in production).
A simple example, not bound to embassy:
```rust
async fn main_inner() -> Result<()> {
       // do something that could return an error
}

pub async fn main() {
     match main_inner().await {
            Ok(_) => {} // do nothing
            Err(e) => {
                 defmt::error!("Error: {:?}", e);
            } 
     }
}
```
