### ISSUE TITLE
GPIO pin not mutablem bur´t no error 

### ISSUE THREAD

**Issue by mschnell1** [embassy-rs/embassy#3659]
in `example-embassy-rp23/src/bin/multicore.rs`  we have
``` 
let led = Output::new(p.PIN_25, Level::Low);
``` 
hence `led` is immutable 

but 
```
#[embassy_executor::task]
async fn core1_task(mut led: Output<'static>) {
    info!("Hello from core 1");
    loop {
        match CHANNEL.receive().await {
            LedState::On => led.set_high(),
``` 

and in `gpios.rs` we see: 
``` 
    pub fn set_high(&mut self) {
        self.pin.set_high()
    }
``` 
hence `led `in fact needs to be mutable

Why does this not result in a compile time error ? 
Obviously this is due to `#[embassy_executor::task] ` 

But seems a bit confusing. 

I unsuccessfully tried to make `led `mutable to use a "in-between" function that calls the Spawner to entangle the code in `executer1.run()`  (as I do spawn some additional task there ) .

Is this intended behavior ? 

(BTW.: in the `blinky `example, we do have and need `let mut led = Output::new(p.PIN_25, Level::Low);` )

**Comment by Dirbaio** [comment]
it's working as intended, you're making it mutable here:

```rust
async fn core1_task(mut led: Output<'static>) {
                    ^^^
                    HERE
```

**Comment by mschnell1** [comment]
Yep. Thanks for answering !
This is obvious.
It feels odd that it's intended to convert an immutable variable to a mutable (in the other context).
I suppose I need to understand it something like "`led `is immutable with respect to core 0 but mutable with respect top core 1" which indeed is what the example is all about. 
But given this, the core1 context does not even need to know about the led variable. 
Hence I tried to "move" it into a function called by "run", but did not yet succeed.

**Comment by Dirbaio** [comment]
in Rust it's the *variables* that are mutable or not, not the *values*. There's no such thing as a "not mutable LED". 

You create a LED and you put it in an immutable variable, then you can't mutate it. However, you can move it to another variable that is mutable, and then you can mutate it.

**Comment by mschnell1** [comment]
I see.  (silly me) 
I also was able to do the "in-between" function.
silly again, I forgot to claim the `static `lifetime for `led`.
