### ISSUE TITLE
BDC event, incomplete data

### ISSUE THREAD

**Issue by erichstuder** [embassy-rs/embassy#3694]
Hello

When i run [wifi_blinky.rs](https://github.com/embassy-rs/embassy/blob/main/examples/rp/src/bin/wifi_blinky.rs) example on RPi Pico W.
I get some warnings in the beginning:

```
2.422150 WARN  BDC event, incomplete data
2.423901 WARN  BDC event, incomplete data
3.319135 INFO  led on!
4.328791 INFO  led off!
...
```

Do you see these warnings as well?
Is it something to worry about?

**Comment by Dirbaio** [comment]
they can be ignored, yes!

**Comment by erichstuder** [comment]
Thank you!
