### ISSUE TITLE
Proposal: embassy-lora 

### ISSUE THREAD

**Issue by lulf** [embassy-rs/embassy#404]
Similar to embassy-net, I'd like to propose adding an embassy-lora module with:

*) async lora radio drivers that works with embassy, i.e. using async SPI
*) rust-lorawan (MAC layer) trait implementations for above radios + radios in embassy-stm32

Then, create examples/embassy-lora with examples of using rust-lorawan with the async radio drivers running with embassy. 

Most of the above exists in drogue-device already, but the trait implementations are not yet fully async. I'd like to do the work on the async versions in embassy if people agree with this.

**Comment by Dirbaio** [comment]
Sounds great to me! The more features, the better!

I don't think I'll be able to help much, I'm not personally invested in LoRa. I can help with API design/consistency if you want to.

**Comment by lulf** [comment]
PR #410

**Comment by MathiasKoch** [comment]
Seems like this can be closed?
