### ISSUE TITLE
STM32 USB (OTG) implementation

### ISSUE THREAD

**Issue by FrozenDroid** [embassy-rs/embassy#557]
Hi. For our upcoming project, we need a USB-OTG implementation. We are using the STM32L476

I see that there is no implementation yet. I'm creating this issue as a track issue to coordinate work.

Has anyone done any research into implementing this in the Embassy HAL?

**Comment by Dirbaio** [comment]
There's this HAL-independent driver that works with all chips with OTG: https://github.com/stm32-rs/synopsys-usb-otg

It should be easy to wrap it with [this](https://github.com/embassy-rs/embassy/blob/master/embassy-hal-common/src/usb/mod.rs), similar to what #539 does with nrf-usbd.

**Comment by FrozenDroid** [comment]
Oh, I entirely missed this. I'll have a look!
