### ISSUE TITLE
UsbSerial hangs in hot loop

### ISSUE THREAD

**Issue by dvdsk** [embassy-rs/embassy#654]
First let me thank you all for making this. Using embassy is so much easier then building on the manufacturer SDKs, async on embedded is fun. 

I am toying around with an stm32f401ccu for some home automation stuff. It will be communicates over UsbSerial with a host linux machine. For testing I wrote a loop that spams a fixed message to the host (complete example [here](https://github.com/evavh/button-panel/tree/min_example/panel)) . On the host I listen on the connection using `cat /dev/ttyACM0`.

```rust
loop {
    trace!("sending text");
    let msg = "This is a fixed size message";
    let mut buf = [0u8; 28];
    buf[..28].copy_from_slice(msg.as_bytes());
    unwrap!(writer.write_all(&buf).await);
    unwrap!(writer.write_all(b"\r\n").await);
    unwrap!(writer.flush().await);
    //Needed, can go as low as 90 before things fail
    Timer::after(Duration::from_millis(200)).await; 
}
```
The loop above works as long as I keep the delay. If I remove it nothing is received on the host and the device stops sending after a while. I suspect when a buffer on the host is full since flush succeeds. 

The setup code matches that of the example _except I had to change the vendor and product id_ or it would not work.

**Comment by Dirbaio** [comment]
Interesting, might be a bug. Your link is 404, could you look into that? Thanks!

**Comment by dvdsk** [comment]
> Interesting, might be a bug. Your link is 404, could you look into that? Thanks!

The repo was set to private it seems therefore the link 404-ed, should be fixed.
