### ISSUE TITLE
embassy.dev using self-signed traefik cert and hsts is enabled - cannot access from chrome or firefox

### ISSUE THREAD

**Issue by bkc** [embassy-rs/embassy#719]
sorry if this is the wrong repo..

I am unable to access https://embassy.dev/ from chrome or firefox

ssl labs reports 

![image](https://user-images.githubusercontent.com/119869/163470912-074cb9cb-bc7a-4229-aca9-0168ce27a58a.png)

and chrome reports that hsts is enabled for the site, therefore the self-signed cert is not accepted.

**Comment by Dirbaio** [comment]
I'm migrating the server, it should be back up in some minutes. Sorry for the trouble!

**Comment by bkc** [comment]
thanks for the fast response. FYI, I was following a link from this page https://tweedegolf.nl/en/blog/70/we-asked-5-people-why-they-like-embedded-rust

**Comment by Dirbaio** [comment]
Fixed now!
