### ISSUE TITLE
nrf UarteWithIdle uses too short a timeout.

### ISSUE THREAD

**Issue by ZoeyR** [embassy-rs/embassy#753]
It appears the math is wrong for the timeout in `UarteWithIdle` on the NRF. It attempts to calculate the time for 40bits of idle but it ends up about half of that, at least for 115200 baud.

At 115200 baud the current timeout is 2788 cycles. Calculated with 0x8000_0000 / (30801920 / 40);
30801920 is `Baudrate::BAUD115200` as a u32.

The timeout _should_ be about 5,555 cycles if my math is correct. Math detailed below:
- 115200 baud is 115200 bits per second
- take 1 / 115200 to get the seconds per bit
- multiply by 40 to get the total time in seconds
- multiply by the timer frequency of 16 million cycles / second to get the number of cycles
- This should be equal to 5,555.5 cycles

I noticed this because the uarte would drop bytes randomly during usage. I increased the timeout by a massive amount (to 100_000 cycles) to see if it fixed the issue and it did. Looking at the math this seems to be the culprit.

**Comment by Dirbaio** [comment]
closing after discussion in https://github.com/embassy-rs/embassy/pull/754
