### ISSUE TITLE
DelayUs rounded down to zero

### ISSUE THREAD

**Issue by caspermeijn** [embassy-rs/embassy#823]
I have synchronous driver that uses `embedded_hal::blocking::delay::DelayUs` for the [reset sequence](https://github.com/almindor/st7789/blob/24968a36149751cef2c9ec28048906f2f07f8d3f/src/lib.rs#L166). However `delay_source.delay_us(10);` gets rounded down to 0, which means the reset pin is 0 seconds active. 

I was thinking that the delay implementation should at least wait 1 tick. Would that the an acceptable solution in this project? If yes, I will create a PR for it.

**Comment by Dirbaio** [comment]
Nice catch. DelayUs/DelayMs should definitely wait for *at least* the requested time, it's OK to wait for more but not to wait for less. 

It probably makes sense for `Duration::from_*` to round up by default? (and also `Duration::as_*` for consistency). 

The alternative is to add `Duration::from_*_rounding_up` and `Duration::as_*_rounding_up` and use these in the `Delay` impls, but it leaves the footgun there for code not using `Delay`...
