### ISSUE TITLE
embassy-sync is missing declared features `std` and `cortex-m`

### ISSUE THREAD

**Issue by G33KatWork** [embassy-rs/embassy#930]
I am not sure if this is actually the case or if I'm doing something wrong and these features can be declared differently, but I think `embassy-sync` is missing the feature declarations for `std` and `cortex-m` in `Cargo.toml`.

If these features are missing, I cannot include them when using the crate. And if I cannot include them, I cannot use the `ThreadModeRawMutex`: https://github.com/embassy-rs/embassy/blob/master/embassy-sync/src/blocking_mutex/raw.rs#L90

There is already a pull-request for `cargo-utils` which seems to also have a missing `std` feature declaration: https://github.com/embassy-rs/embassy/pull/902

**Comment by lulf** [comment]
Thanks for the PR, I've missed the PR that fixes it for embassy-util, but submitted one that fixes it for embassy-sync. The cortex_m flag is automatically derived by the build script in embassy-sync, so that should work as expected.
